"""Embed the canonical fixed-formation policy JSON into the C++ engine.

The C++ standalone optimizer compiles a single binary with no runtime dependency on
the Python reference or on a policy file path, so the canonical policy document is
materialised as a C++ raw string literal. This mirrors the Go `go:embed` and Rust
`include_str!` embeddings so all four engines consume the exact same bytes.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POLICY = ROOT / "coordination" / "fixed-formation-20261006" / "fixed-formation-policy.json"
TARGET = ROOT / "coordination" / "native-preparation" / "cpp" / "standalone-optimizer" / "fixed_formation_policy.inc"
CHUNK_BYTES = 12000


def main() -> int:
    text = POLICY.read_text(encoding="utf-8")
    document = json.loads(text)
    canonical = json.dumps(document, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    # MSVC caps a single string literal at 16380 characters, so emit adjacent chunks. Each chunk uses
    # its own short raw-string delimiter (<= 16 characters) to stay within the compiler limit.
    chunks = [canonical[index:index + CHUNK_BYTES] for index in range(0, len(canonical), CHUNK_BYTES)]
    lines = [
        "// Generated by tools/embed_cpp_fixed_policy.py -- do not edit by hand.",
        "// Canonical fixed-formation policy (schema ka-fixed-formation-policy-1).",
        "static const char kFixedFormationPolicyJson[] =",
    ]
    for index, chunk in enumerate(chunks):
        delimiter = f"KAFFP{index}"
        if f"){delimiter}\"" in chunk:
            raise SystemExit("policy chunk contains the raw-string delimiter; choose another delimiter")
        suffix = ";" if index == len(chunks) - 1 else ""
        lines.append(f'    R"{delimiter}({chunk}){delimiter}"{suffix}')
    body = "\n".join(lines) + "\n"
    TARGET.write_text(body, encoding="utf-8")
    digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    print(json.dumps({"target": str(TARGET), "policyHash": document.get("policyHash"),
                      "canonicalSha256": digest, "bytes": len(canonical)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
