"""Controlled original skill queues feeding boss re-entry; no setup prediction."""
import json
from itertools import product
from combat_initial_state import EVIDENCE
from combat_entities import CombatEntities
from combat_commands import enqueue_skill_command, execute_skill_queue
from combat_shared_resolution import dispatch_shared_attack
from combat_states import change_fighter_state, enter_damaging, update_damaging, exit_damaging, enter_leaving_special, update_leaving
from combat_tick import update_fighters

rows={s['id']:s for s in json.loads((EVIDENCE/'weapon-skill-profiles.json').read_text(encoding='utf-8'))['skills']}
examples=[]
for skill_id,other_counters,boss_counter,before,alternate_misses in product(
        (22,23,24,25,109,110),(0,1,3),(False,True),(False,True),(False,True)):
    world=CombatEntities(100,[]);boss=world.allocate();other=world.allocate()
    world.add_component(boss,'AI',dict(board={4:0,5:3,6:1,7:0},long_board={},commands=[],path=[]))
    world.add_component(boss,'Position',[0.,0.,72.,0.,0.,0.,None])
    world.add_component(boss,'Speed',[0.,0.,0.]);world.add_component(boss,'Direction',[2])
    world.add_component(boss,'Parameter',dict(parameters={10:dict(rawValue=1,rawMax=1)}))
    unit=world.fighter(boss);queue=[];animation=dict(rate=1,frame=0)
    def enqueue(target,identity):enqueue_skill_command(queue,target,rows[identity],target_exists=True)
    enqueue(boss,skill_id)
    for _ in range(other_counters):enqueue(other,26)
    if boss_counter:enqueue(boss,26)
    enqueue(boss,skill_id)
    initial_queue=[dict(c) for c in queue];rewards=[];attempts=[];landed=[];tick=-1
    def leave(fighter):
        enter_leaving_special(fighter,3,lambda u:True,lambda u:True,lambda *a:None,
                              lambda u:None,lambda:rewards.append(tick),lambda sound:None)
    def change(fighter,state):
        change_fighter_state(fighter,state,{3:lambda u:None,6:lambda u:exit_damaging(u,3),8:lambda u:None},
                             {6:lambda u:enter_damaging(u,lambda *a:None),8:leave})
    def update(fighter,state):
        if state==6:
            update_damaging(fighter,lambda u:u['parameters'][10]['rawValue'],lambda u:False,lambda u:True,
                lambda u:True,lambda:False,lambda u:3,lambda u:None,change)
        elif state==8:update_leaving(fighter)
    def use(command,index):
        attempts.append(dict(tick=tick,target=command['target'],skill=command['skill'],index=index))
        # Teammate-directed Counter consumes queue time, but cannot hit this boss.
        if command['target']!=boss:return
        ordinal=sum(a['target']==boss for a in attempts)-1
        hit=not alternate_misses or ordinal%2==0
        if hit:landed.append(tick)
        dispatch_shared_attack(world,[dict(target=boss,hit=hit,damage=1)],lambda r:None,change)
    def release():execute_skill_queue(queue,lambda c:rows[c['skill']],animation,lambda a:None,use)
    for tick in range(300):
        if before:release()
        update_fighters([[unit]],2,update,lambda u:None)
        if not before:release()
    expected=[]
    for index,t in enumerate(landed):
        due=t+(6 if before else 7)
        following=landed[index+1] if index+1<len(landed) else 10000
        if (due<following if before else due<=following):expected.append(due)
    assert rewards==expected,(initial_queue,rewards,expected)
    assert not queue and unit['parameters'][10]['rawValue']==0
    assert len(attempts)==2*rows[skill_id]['count']+other_counters+int(boss_counter)
    assert sum(a['target']==other for a in attempts)==other_counters
    examples.append(dict(skillId=skill_id,otherCounters=other_counters,bossCounter=boss_counter,
        releaseBeforeBoss=before,alternatingBossMisses=alternate_misses,queue=initial_queue,
        attempts=attempts,landedBossTicks=landed,chestCallbackTicks=rewards,chestCallbacks=len(rewards)))
report=dict(controlledQueuedChestCases=len(examples),logicalTicks=len(examples)*300,examples=examples,
    findings=['Original multi-hit and Counter command clocks now feed zero-HP boss re-entry in one controlled fixture.',
              'Counter against a teammate retains that target and consumes queue time; it is not automatically another boss attack.',
              'Boss-directed landed-hit spacing, not total queued hit count, determines these repeated Leaving callbacks.'],
    limits=['Portable composition; queue entries and hit outcomes supplied, not generated by a full encounter.',
            'Use callback bypasses skill eligibility, MP, invocation, damage math and defensive reactions.',
            'Encounter held active; no healer, item use, departure flight, RNG or final prize settlement.',
            'No maximum yield or optimal queue/stat recommendation follows from this controlled fixture.'])
(EVIDENCE/'queued-chest-checks.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
print(json.dumps({k:v for k,v in report.items() if k!='examples'}))
