"""Extract original surround-effect entries; no website simulation assumptions.
Run from the workspace root with .venv/Scripts/python.exe.
"""
import csv
import json
import struct
from collections import Counter
from pathlib import Path
import export_assembled_facility_icons as source

OUT = source.EVIDENCE / 'surround-effects'
OUT.mkdir(exist_ok=True)
lookup = {int(r[0]): r for r in csv.reader((source.ROOT / 'data/sheet-research/raw-copies/KA GameData - Facility_lookup.csv').open(encoding='utf-8-sig')) if r[0].isdigit()}
categories = ['Stat EXP', 'Recovery', 'Warehouse capacity', 'Maximum HP', 'Targeting cost']
stats = {10:'HP',11:'MP',12:'Energy',13:'Attack',14:'Defense',15:'Agility',16:'Luck',18:'Intelligence',19:'Dexterity',20:'Gathering',21:'Movement',22:'Love'}

def f32(x):
    return struct.unpack('<f', struct.pack('<f', x))[0]

def value_at(low, high, level, limit=0):
    # GetAroundEffectValue -> Easing, amplitude 0, 99 steps. Native float32.
    level = min(level, limit) if limit else level
    step = level - 1
    if step < 0: return low
    if step >= 99: return high
    return int(f32(f32(f32(step / 99) * (high-low)) + low))

records = []
checks = 0
chips = source.table('MapChip')
for fid, raw in source.table('Facility').items():
    row = lookup[fid]
    # Variable-length earlier arrays shift absolute columns in original rows.
    # Surround triples are at a fixed offset from the end, not fixed column 80.
    original = raw[-57:-45]
    assert original == row[84:96], fid
    checks += 1
    effects = []
    for slot in range(3):
        cat, kind, low, high = map(int, original[slot*4:slot*4+4])
        if cat == -1: continue
        assert 0 <= cat < 5
        effects.append(dict(slot=slot, category=cat, categoryName=categories[cat], type=kind,
                            stat=stats.get(kind) if cat == 0 else None, minimum=low, maximum=high,
                            samples={str(level):value_at(low,high,level) for level in [1,25,50,75,100]}))
        assert value_at(low,high,1)==low and value_at(low,high,100)==high
        assert value_at(low,high,100,25)==value_at(low,high,25)
        checks += 3
    if effects:
        map_chips = [dict(id=int(c[0]),areaMerge=bool(int(c[-1])&2048),componentSize=list(map(int,c[22:24])),unitSize=list(map(int,c[24:26]))) for c in chips.values() if c[15]=='1' and int(c[16])==fid]
        records.append(dict(facilityId=fid,name=row[1],effects=effects,mapChips=map_chips,immuneAsTarget=bool(int(raw[-1])&2097152)))

counts=Counter(e['categoryName'] for r in records for e in r['effects'])
payload=dict(status='Original table extraction with static native-code interpretation; no original-game runtime validation',
             source='English.lproj/Facility.txt, cross-checked against Facility_lookup.csv; MapChip.txt',
             sourceFacilityCount=len(records),effectEntryCount=sum(counts.values()),categoryCounts=dict(counts),
             fixedRange=3,levelFormula='float32 linear interpolation from minimum to maximum over levels 1..100; truncate toward zero; nonzero source limit caps shared FacilityData level',
             facilities=records,checks=checks)
(OUT/'catalog.json').write_text(json.dumps(payload,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
lines=['# Original surround-effect catalog','', 'Generated by `tools/recovery/recover_surround_effects.py`. Values are percent points; category 2 has no active original entries. Level is shared FacilityData upgrade level, capped by the source limit.','', '| Facility | Effect | Level 1 | Level 50 | Level 100 |','|---|---|---:|---:|---:|']
for r in records:
    for e in r['effects']:
        label=f"{e['stat']} EXP" if e['category']==0 else e['categoryName']
        lines.append(f"| {r['name']} ({r['facilityId']}) | {label} | {e['samples']['1']} | {e['samples']['50']} | {e['samples']['100']} |")
(OUT/'catalog.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps({k:payload[k] for k in ['sourceFacilityCount','effectEntryCount','categoryCounts','checks']}))
