#pragma once
#include <cstddef>
#include <cstdint>
#include <nlohmann/json.hpp>

struct KaBattleReport {
    std::int32_t status{};
    std::int32_t ticks{};
    std::int32_t verdict{};
    std::int32_t verdict_tick{};
    std::int32_t battle_state{};
    std::int32_t battle_frame{};
    std::int32_t finish_policy{};
    std::int32_t ending_gate_tick{};
    std::int32_t ending_confirmed{};
    std::int32_t ending_counter{};
    std::int32_t prize_callbacks{};
    std::int32_t pre_verdict_prize_callbacks{};
    std::int32_t unresolved_commands{};
    std::int32_t pending_projectiles{};
    std::int32_t active_damage_or_leaving{};
    std::int32_t math_draws{};
    std::int32_t lib_draws{};
    std::int32_t certificate_held{};
    std::int32_t certificate_frame{};
    std::int32_t certificate_pending{};
    std::int32_t late_hold_frame{};
    std::int32_t pending_at_verdict{};
    std::int32_t pending_final{};
    std::int32_t post_certificate_delta{};
    std::int32_t observations{};
    std::int32_t verdict_observations{};
    std::int32_t clauses[4]{};
    std::int32_t boss_hp{};
    std::int32_t boss_state{};
    std::int32_t stored_target_holders{};
    std::int32_t queued_command_holders{};
    std::int32_t scope_allowed{};
    std::int32_t heals{};
    std::int32_t attack_attempts{};
    std::int32_t survivors{};
    std::int64_t own_hp{};
    std::int64_t own_hp_max{};
    std::int32_t own_present{};
    std::int32_t resource_uses{};
    std::int32_t progress_boss{};
    std::int32_t progress_boss_death_tick{};
    std::int32_t progress_boss_leaving_tick{};
    std::int32_t progress_stored_at_death{};
    std::int32_t progress_stored_targeting_boss_at_death{};
    std::int32_t progress_stored_target_holders_at_death{};
    std::int32_t progress_commands_targeting_boss{};
    std::int32_t progress_commands_targeting_boss_released{};
    std::int32_t progress_max_stored{};
    std::int32_t progress_max_targeting_boss{};
    std::int32_t progress_target_holders_peak{};
    std::int32_t progress_post_death_reentries{};
    std::int32_t progress_post_death_leavings{};
    std::int32_t progress_post_death_prizes{};
    std::int32_t progress_released_after_death{};
    std::int32_t progress_released_after_death_targeting_boss{};
    std::int32_t progress_first_release_after_death{};
    std::int32_t progress_last_release_after_death{};
    std::int32_t mp_watch_count{};
    std::int32_t mp_identity[2]{};
    std::int32_t mp_min[2]{};
    std::int32_t mp_min_percent[2]{};
    std::int32_t mp_low[2]{};
    std::int32_t mp_first_low_tick[2]{};
    std::int32_t mp_first_low_phase[2]{};
    std::int32_t mp_zero[2]{};
    std::int32_t herb_stock_start{};
    std::int32_t herb_stock_remaining{};
    std::int32_t herb_max_uses{};
    std::int32_t herb_use_count{};
    std::int32_t herb_log_count{};
    std::int32_t herb_use_tick[16]{};
    std::int32_t herb_use_phase[16]{};
    std::int32_t herb_use_source[16]{};
    std::int32_t herb_use_ok[16]{};
};

static_assert(sizeof(KaBattleReport) == 584);
static_assert(offsetof(KaBattleReport, status) == 0);
static_assert(offsetof(KaBattleReport, ticks) == 4);
static_assert(offsetof(KaBattleReport, verdict) == 8);
static_assert(offsetof(KaBattleReport, verdict_tick) == 12);
static_assert(offsetof(KaBattleReport, battle_state) == 16);
static_assert(offsetof(KaBattleReport, battle_frame) == 20);
static_assert(offsetof(KaBattleReport, finish_policy) == 24);
static_assert(offsetof(KaBattleReport, ending_gate_tick) == 28);
static_assert(offsetof(KaBattleReport, ending_confirmed) == 32);
static_assert(offsetof(KaBattleReport, ending_counter) == 36);
static_assert(offsetof(KaBattleReport, prize_callbacks) == 40);
static_assert(offsetof(KaBattleReport, pre_verdict_prize_callbacks) == 44);
static_assert(offsetof(KaBattleReport, unresolved_commands) == 48);
static_assert(offsetof(KaBattleReport, pending_projectiles) == 52);
static_assert(offsetof(KaBattleReport, active_damage_or_leaving) == 56);
static_assert(offsetof(KaBattleReport, math_draws) == 60);
static_assert(offsetof(KaBattleReport, lib_draws) == 64);
static_assert(offsetof(KaBattleReport, certificate_held) == 68);
static_assert(offsetof(KaBattleReport, certificate_frame) == 72);
static_assert(offsetof(KaBattleReport, certificate_pending) == 76);
static_assert(offsetof(KaBattleReport, late_hold_frame) == 80);
static_assert(offsetof(KaBattleReport, pending_at_verdict) == 84);
static_assert(offsetof(KaBattleReport, pending_final) == 88);
static_assert(offsetof(KaBattleReport, post_certificate_delta) == 92);
static_assert(offsetof(KaBattleReport, observations) == 96);
static_assert(offsetof(KaBattleReport, verdict_observations) == 100);
static_assert(offsetof(KaBattleReport, clauses) == 104);
static_assert(offsetof(KaBattleReport, boss_hp) == 120);
static_assert(offsetof(KaBattleReport, boss_state) == 124);
static_assert(offsetof(KaBattleReport, stored_target_holders) == 128);
static_assert(offsetof(KaBattleReport, queued_command_holders) == 132);
static_assert(offsetof(KaBattleReport, scope_allowed) == 136);
static_assert(offsetof(KaBattleReport, heals) == 140);
static_assert(offsetof(KaBattleReport, attack_attempts) == 144);
static_assert(offsetof(KaBattleReport, survivors) == 148);
static_assert(offsetof(KaBattleReport, own_hp) == 152);
static_assert(offsetof(KaBattleReport, own_hp_max) == 160);
static_assert(offsetof(KaBattleReport, own_present) == 168);
static_assert(offsetof(KaBattleReport, resource_uses) == 172);
static_assert(offsetof(KaBattleReport, progress_boss) == 176);
static_assert(offsetof(KaBattleReport, progress_boss_death_tick) == 180);
static_assert(offsetof(KaBattleReport, progress_boss_leaving_tick) == 184);
static_assert(offsetof(KaBattleReport, progress_stored_at_death) == 188);
static_assert(offsetof(KaBattleReport, progress_stored_targeting_boss_at_death) == 192);
static_assert(offsetof(KaBattleReport, progress_stored_target_holders_at_death) == 196);
static_assert(offsetof(KaBattleReport, progress_commands_targeting_boss) == 200);
static_assert(offsetof(KaBattleReport, progress_commands_targeting_boss_released) == 204);
static_assert(offsetof(KaBattleReport, progress_max_stored) == 208);
static_assert(offsetof(KaBattleReport, progress_max_targeting_boss) == 212);
static_assert(offsetof(KaBattleReport, progress_target_holders_peak) == 216);
static_assert(offsetof(KaBattleReport, progress_post_death_reentries) == 220);
static_assert(offsetof(KaBattleReport, progress_post_death_leavings) == 224);
static_assert(offsetof(KaBattleReport, progress_post_death_prizes) == 228);
static_assert(offsetof(KaBattleReport, progress_released_after_death) == 232);
static_assert(offsetof(KaBattleReport, progress_released_after_death_targeting_boss) == 236);
static_assert(offsetof(KaBattleReport, progress_first_release_after_death) == 240);
static_assert(offsetof(KaBattleReport, progress_last_release_after_death) == 244);
static_assert(offsetof(KaBattleReport, mp_watch_count) == 248);
static_assert(offsetof(KaBattleReport, mp_identity) == 252);
static_assert(offsetof(KaBattleReport, mp_min) == 260);
static_assert(offsetof(KaBattleReport, mp_min_percent) == 268);
static_assert(offsetof(KaBattleReport, mp_low) == 276);
static_assert(offsetof(KaBattleReport, mp_first_low_tick) == 284);
static_assert(offsetof(KaBattleReport, mp_first_low_phase) == 292);
static_assert(offsetof(KaBattleReport, mp_zero) == 300);
static_assert(offsetof(KaBattleReport, herb_stock_start) == 308);
static_assert(offsetof(KaBattleReport, herb_stock_remaining) == 312);
static_assert(offsetof(KaBattleReport, herb_max_uses) == 316);
static_assert(offsetof(KaBattleReport, herb_use_count) == 320);
static_assert(offsetof(KaBattleReport, herb_log_count) == 324);
static_assert(offsetof(KaBattleReport, herb_use_tick) == 328);
static_assert(offsetof(KaBattleReport, herb_use_phase) == 392);
static_assert(offsetof(KaBattleReport, herb_use_source) == 456);
static_assert(offsetof(KaBattleReport, herb_use_ok) == 520);

inline nlohmann::json report_json(const KaBattleReport& report) {
    nlohmann::json result = nlohmann::json::object();
    result["status"] = report.status;
    result["ticks"] = report.ticks;
    result["verdict"] = report.verdict;
    result["verdict_tick"] = report.verdict_tick;
    result["battle_state"] = report.battle_state;
    result["battle_frame"] = report.battle_frame;
    result["finish_policy"] = report.finish_policy;
    result["ending_gate_tick"] = report.ending_gate_tick;
    result["ending_confirmed"] = report.ending_confirmed;
    result["ending_counter"] = report.ending_counter;
    result["prize_callbacks"] = report.prize_callbacks;
    result["pre_verdict_prize_callbacks"] = report.pre_verdict_prize_callbacks;
    result["unresolved_commands"] = report.unresolved_commands;
    result["pending_projectiles"] = report.pending_projectiles;
    result["active_damage_or_leaving"] = report.active_damage_or_leaving;
    result["math_draws"] = report.math_draws;
    result["lib_draws"] = report.lib_draws;
    result["certificate_held"] = report.certificate_held;
    result["certificate_frame"] = report.certificate_frame;
    result["certificate_pending"] = report.certificate_pending;
    result["late_hold_frame"] = report.late_hold_frame;
    result["pending_at_verdict"] = report.pending_at_verdict;
    result["pending_final"] = report.pending_final;
    result["post_certificate_delta"] = report.post_certificate_delta;
    result["observations"] = report.observations;
    result["verdict_observations"] = report.verdict_observations;
    result["clauses"] = nlohmann::json::array({report.clauses[0], report.clauses[1], report.clauses[2], report.clauses[3]});
    result["boss_hp"] = report.boss_hp;
    result["boss_state"] = report.boss_state;
    result["stored_target_holders"] = report.stored_target_holders;
    result["queued_command_holders"] = report.queued_command_holders;
    result["scope_allowed"] = report.scope_allowed;
    result["heals"] = report.heals;
    result["attack_attempts"] = report.attack_attempts;
    result["survivors"] = report.survivors;
    result["own_hp"] = report.own_hp;
    result["own_hp_max"] = report.own_hp_max;
    result["own_present"] = report.own_present;
    result["resource_uses"] = report.resource_uses;
    result["progress_boss"] = report.progress_boss;
    result["progress_boss_death_tick"] = report.progress_boss_death_tick;
    result["progress_boss_leaving_tick"] = report.progress_boss_leaving_tick;
    result["progress_stored_at_death"] = report.progress_stored_at_death;
    result["progress_stored_targeting_boss_at_death"] = report.progress_stored_targeting_boss_at_death;
    result["progress_stored_target_holders_at_death"] = report.progress_stored_target_holders_at_death;
    result["progress_commands_targeting_boss"] = report.progress_commands_targeting_boss;
    result["progress_commands_targeting_boss_released"] = report.progress_commands_targeting_boss_released;
    result["progress_max_stored"] = report.progress_max_stored;
    result["progress_max_targeting_boss"] = report.progress_max_targeting_boss;
    result["progress_target_holders_peak"] = report.progress_target_holders_peak;
    result["progress_post_death_reentries"] = report.progress_post_death_reentries;
    result["progress_post_death_leavings"] = report.progress_post_death_leavings;
    result["progress_post_death_prizes"] = report.progress_post_death_prizes;
    result["progress_released_after_death"] = report.progress_released_after_death;
    result["progress_released_after_death_targeting_boss"] = report.progress_released_after_death_targeting_boss;
    result["progress_first_release_after_death"] = report.progress_first_release_after_death;
    result["progress_last_release_after_death"] = report.progress_last_release_after_death;
    result["mp_watch_count"] = report.mp_watch_count;
    result["mp_identity"] = nlohmann::json::array({report.mp_identity[0], report.mp_identity[1]});
    result["mp_min"] = nlohmann::json::array({report.mp_min[0], report.mp_min[1]});
    result["mp_min_percent"] = nlohmann::json::array({report.mp_min_percent[0], report.mp_min_percent[1]});
    result["mp_low"] = nlohmann::json::array({report.mp_low[0], report.mp_low[1]});
    result["mp_first_low_tick"] = nlohmann::json::array({report.mp_first_low_tick[0], report.mp_first_low_tick[1]});
    result["mp_first_low_phase"] = nlohmann::json::array({report.mp_first_low_phase[0], report.mp_first_low_phase[1]});
    result["mp_zero"] = nlohmann::json::array({report.mp_zero[0], report.mp_zero[1]});
    result["herb_stock_start"] = report.herb_stock_start;
    result["herb_stock_remaining"] = report.herb_stock_remaining;
    result["herb_max_uses"] = report.herb_max_uses;
    result["herb_use_count"] = report.herb_use_count;
    result["herb_log_count"] = report.herb_log_count;
    result["herb_use_tick"] = nlohmann::json::array({report.herb_use_tick[0], report.herb_use_tick[1], report.herb_use_tick[2], report.herb_use_tick[3], report.herb_use_tick[4], report.herb_use_tick[5], report.herb_use_tick[6], report.herb_use_tick[7], report.herb_use_tick[8], report.herb_use_tick[9], report.herb_use_tick[10], report.herb_use_tick[11], report.herb_use_tick[12], report.herb_use_tick[13], report.herb_use_tick[14], report.herb_use_tick[15]});
    result["herb_use_phase"] = nlohmann::json::array({report.herb_use_phase[0], report.herb_use_phase[1], report.herb_use_phase[2], report.herb_use_phase[3], report.herb_use_phase[4], report.herb_use_phase[5], report.herb_use_phase[6], report.herb_use_phase[7], report.herb_use_phase[8], report.herb_use_phase[9], report.herb_use_phase[10], report.herb_use_phase[11], report.herb_use_phase[12], report.herb_use_phase[13], report.herb_use_phase[14], report.herb_use_phase[15]});
    result["herb_use_source"] = nlohmann::json::array({report.herb_use_source[0], report.herb_use_source[1], report.herb_use_source[2], report.herb_use_source[3], report.herb_use_source[4], report.herb_use_source[5], report.herb_use_source[6], report.herb_use_source[7], report.herb_use_source[8], report.herb_use_source[9], report.herb_use_source[10], report.herb_use_source[11], report.herb_use_source[12], report.herb_use_source[13], report.herb_use_source[14], report.herb_use_source[15]});
    result["herb_use_ok"] = nlohmann::json::array({report.herb_use_ok[0], report.herb_use_ok[1], report.herb_use_ok[2], report.herb_use_ok[3], report.herb_use_ok[4], report.herb_use_ok[5], report.herb_use_ok[6], report.herb_use_ok[7], report.herb_use_ok[8], report.herb_use_ok[9], report.herb_use_ok[10], report.herb_use_ok[11], report.herb_use_ok[12], report.herb_use_ok[13], report.herb_use_ok[14], report.herb_use_ok[15]});
    return result;
}
