/* eslint-disable */
// Auto-generated by scripts/export-f2-semantic-layer-fixture.mjs
// generatedAt: 2026-05-16T03:27:27.673Z
// source: C:/Users/anisb/OneDrive/Desktop/replit Kingdom Adventurers - Copy/KA-Website/artifacts/kingdom-adventures/tmp/map-section-a-f2-mapchip-semantic-groups.json

export type F2SemanticGroup =
  | "terrain/ground/water"
  | "road/path/traffic/buildable-related"
  | "special overlay/runtime-marker"
  | "unknown";

export interface F2MapChipRuntimeMeta {
  readonly chipId: number;
  readonly semanticGroup: F2SemanticGroup;
  readonly type: number | null;
  readonly category: number | null;
  readonly movementCost: number | null;
  readonly targetCost: number | null;
  readonly layer: number | null;
  readonly sizeWidth: number | null;
  readonly sizeHeight: number | null;
  readonly flags: readonly string[];
  readonly relatedDataType: number | null;
  readonly relatedDataId: number | null;
  readonly f3Distribution: Readonly<Record<number, number>>;
  readonly f4Distribution: Readonly<Record<number, number>>;
}

export const OBSERVED_F2_MAPCHIP_IDS: readonly number[] = [
  14,
  15,
  16,
  17,
  18,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  38,
  39,
  41,
  42,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  69,
  70,
  71,
  72,
  73,
  74,
  91
];

export const F2_RUNTIME_META_BY_ID: Readonly<Record<number, F2MapChipRuntimeMeta>> = {
  "14": {
    "chipId": 14,
    "semanticGroup": "terrain/ground/water",
    "type": 12,
    "category": 11,
    "movementCost": 5,
    "targetCost": 5,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "No Construction",
      "No Destruct",
      "Parameter",
      "Wander Target"
    ],
    "relatedDataType": 2,
    "relatedDataId": 39,
    "f3Distribution": {
      "0": 890
    },
    "f4Distribution": {
      "1": 890
    }
  },
  "15": {
    "chipId": 15,
    "semanticGroup": "unknown",
    "type": 12,
    "category": 9,
    "movementCost": 5,
    "targetCost": 5,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "No Construction",
      "No Destruct",
      "Parameter",
      "Wander Target"
    ],
    "relatedDataType": 2,
    "relatedDataId": 40,
    "f3Distribution": {
      "0": 658
    },
    "f4Distribution": {
      "1": 658
    }
  },
  "16": {
    "chipId": 16,
    "semanticGroup": "unknown",
    "type": 12,
    "category": 13,
    "movementCost": 5,
    "targetCost": 5,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "No Construction",
      "No Destruct",
      "Parameter",
      "Wander Target"
    ],
    "relatedDataType": 2,
    "relatedDataId": 41,
    "f3Distribution": {
      "0": 313
    },
    "f4Distribution": {
      "1": 313
    }
  },
  "17": {
    "chipId": 17,
    "semanticGroup": "unknown",
    "type": 12,
    "category": 10,
    "movementCost": 5,
    "targetCost": 5,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "No Construction",
      "No Destruct",
      "Parameter",
      "Wander Target"
    ],
    "relatedDataType": 2,
    "relatedDataId": 42,
    "f3Distribution": {
      "0": 297
    },
    "f4Distribution": {
      "1": 297
    }
  },
  "18": {
    "chipId": 18,
    "semanticGroup": "terrain/ground/water",
    "type": 12,
    "category": 12,
    "movementCost": 5,
    "targetCost": 5,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "No Construction",
      "No Destruct",
      "Parameter",
      "Wander Target"
    ],
    "relatedDataType": 2,
    "relatedDataId": 43,
    "f3Distribution": {
      "0": 456
    },
    "f4Distribution": {
      "1": 456
    }
  },
  "28": {
    "chipId": 28,
    "semanticGroup": "special overlay/runtime-marker",
    "type": 11,
    "category": 28,
    "movementCost": 999,
    "targetCost": 999,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "No Construction",
      "No Destruct",
      "Placable"
    ],
    "relatedDataType": 0,
    "relatedDataId": -1,
    "f3Distribution": {
      "0": 1356
    },
    "f4Distribution": {
      "1": 1356
    }
  },
  "29": {
    "chipId": 29,
    "semanticGroup": "terrain/ground/water",
    "type": 11,
    "category": 1,
    "movementCost": 999,
    "targetCost": 999,
    "layer": 0,
    "sizeWidth": 6,
    "sizeHeight": 6,
    "flags": [
      "No Destruct",
      "Placable",
      "Soil Only",
      "Terrain Only"
    ],
    "relatedDataType": 1,
    "relatedDataId": 11,
    "f3Distribution": {
      "0": 1404
    },
    "f4Distribution": {
      "1": 1404
    }
  },
  "30": {
    "chipId": 30,
    "semanticGroup": "terrain/ground/water",
    "type": 11,
    "category": 1,
    "movementCost": 999,
    "targetCost": 999,
    "layer": 0,
    "sizeWidth": 6,
    "sizeHeight": 8,
    "flags": [
      "No Destruct",
      "Placable",
      "Soil Only",
      "Terrain Only"
    ],
    "relatedDataType": 1,
    "relatedDataId": 12,
    "f3Distribution": {
      "0": 1374
    },
    "f4Distribution": {
      "1": 1374
    }
  },
  "31": {
    "chipId": 31,
    "semanticGroup": "terrain/ground/water",
    "type": 11,
    "category": 1,
    "movementCost": 999,
    "targetCost": 999,
    "layer": 0,
    "sizeWidth": 8,
    "sizeHeight": 8,
    "flags": [
      "No Destruct",
      "Placable",
      "Soil Only",
      "Terrain Only"
    ],
    "relatedDataType": 1,
    "relatedDataId": 13,
    "f3Distribution": {
      "1": 842
    },
    "f4Distribution": {
      "0": 842
    }
  },
  "32": {
    "chipId": 32,
    "semanticGroup": "terrain/ground/water",
    "type": 11,
    "category": 1,
    "movementCost": 999,
    "targetCost": 999,
    "layer": 0,
    "sizeWidth": 8,
    "sizeHeight": 10,
    "flags": [
      "No Destruct",
      "Placable",
      "Soil Only",
      "Terrain Only"
    ],
    "relatedDataType": 1,
    "relatedDataId": 14,
    "f3Distribution": {
      "1": 700
    },
    "f4Distribution": {
      "0": 700
    }
  },
  "33": {
    "chipId": 33,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 20,
    "category": 19,
    "movementCost": 0,
    "targetCost": 0,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Out Territory OK",
      "Overridable",
      "Parameter",
      "Placable",
      "Soil Only",
      "Straight Select",
      "Terrain Only",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 3,
    "f3Distribution": {
      "1": 633
    },
    "f4Distribution": {
      "0": 633
    }
  },
  "34": {
    "chipId": 34,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 20,
    "category": 19,
    "movementCost": 0,
    "targetCost": 0,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Out Territory OK",
      "Overridable",
      "Parameter",
      "Placable",
      "Soil Only",
      "Straight Select",
      "Terrain Only",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 4,
    "f3Distribution": {
      "1": 3170
    },
    "f4Distribution": {
      "0": 3170
    }
  },
  "38": {
    "chipId": 38,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 6,
    "category": 3,
    "movementCost": 10,
    "targetCost": 10,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Area Merge",
      "Land Only",
      "No Destruct",
      "Overridable",
      "Range Select",
      "Wall Place",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 49,
    "f3Distribution": {
      "0": 712
    },
    "f4Distribution": {
      "1": 712
    }
  },
  "39": {
    "chipId": 39,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 6,
    "category": 3,
    "movementCost": 10,
    "targetCost": 10,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Area Merge",
      "Land Only",
      "No Destruct",
      "Overridable",
      "Range Select",
      "Wall Place",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 50,
    "f3Distribution": {
      "0": 550
    },
    "f4Distribution": {
      "1": 550
    }
  },
  "41": {
    "chipId": 41,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 6,
    "category": 3,
    "movementCost": 10,
    "targetCost": 10,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Area Merge",
      "Land Only",
      "No Destruct",
      "Overridable",
      "Range Select",
      "Wall Place",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 52,
    "f3Distribution": {
      "0": 525
    },
    "f4Distribution": {
      "1": 525
    }
  },
  "42": {
    "chipId": 42,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 6,
    "category": 3,
    "movementCost": 10,
    "targetCost": 10,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Area Merge",
      "Land Only",
      "No Destruct",
      "Overridable",
      "Range Select",
      "Wall Place",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 53,
    "f3Distribution": {
      "0": 180
    },
    "f4Distribution": {
      "1": 180
    }
  },
  "46": {
    "chipId": 46,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 6,
    "category": 3,
    "movementCost": 10,
    "targetCost": 10,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Area Merge",
      "Land Only",
      "No Destruct",
      "Overridable",
      "Range Select",
      "Wall Place",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 57,
    "f3Distribution": {
      "0": 504
    },
    "f4Distribution": {
      "1": 504
    }
  },
  "47": {
    "chipId": 47,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 6,
    "category": 3,
    "movementCost": 10,
    "targetCost": 10,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Area Merge",
      "Land Only",
      "No Destruct",
      "Overridable",
      "Range Select",
      "Wall Place",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 58,
    "f3Distribution": {
      "0": 124
    },
    "f4Distribution": {
      "1": 124
    }
  },
  "48": {
    "chipId": 48,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 6,
    "category": 3,
    "movementCost": 10,
    "targetCost": 10,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Area Merge",
      "Land Only",
      "No Destruct",
      "Overridable",
      "Range Select",
      "Wall Place",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 59,
    "f3Distribution": {
      "0": 97
    },
    "f4Distribution": {
      "1": 97
    }
  },
  "49": {
    "chipId": 49,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 6,
    "category": 3,
    "movementCost": 10,
    "targetCost": 10,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Area Merge",
      "Land Only",
      "No Destruct",
      "Overridable",
      "Range Select",
      "Wall Place",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 60,
    "f3Distribution": {
      "0": 56
    },
    "f4Distribution": {
      "1": 56
    }
  },
  "50": {
    "chipId": 50,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 6,
    "category": 3,
    "movementCost": 10,
    "targetCost": 10,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Area Merge",
      "Land Only",
      "No Destruct",
      "Overridable",
      "Range Select",
      "Wall Place",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 62,
    "f3Distribution": {
      "0": 39
    },
    "f4Distribution": {
      "1": 39
    }
  },
  "51": {
    "chipId": 51,
    "semanticGroup": "road/path/traffic/buildable-related",
    "type": 6,
    "category": 3,
    "movementCost": 10,
    "targetCost": 10,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Area Merge",
      "Land Only",
      "No Destruct",
      "Overridable",
      "Range Select",
      "Wall Place",
      "Wander Target"
    ],
    "relatedDataType": 1,
    "relatedDataId": 61,
    "f3Distribution": {
      "0": 1337
    },
    "f4Distribution": {
      "1": 1337
    }
  },
  "52": {
    "chipId": 52,
    "semanticGroup": "unknown",
    "type": 24,
    "category": 39,
    "movementCost": 999,
    "targetCost": 999,
    "layer": 2,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Floor Only",
      "No Destruct"
    ],
    "relatedDataType": 0,
    "relatedDataId": -1,
    "f3Distribution": {
      "0": 1344
    },
    "f4Distribution": {
      "1": 1344
    }
  },
  "53": {
    "chipId": 53,
    "semanticGroup": "unknown",
    "type": 24,
    "category": 39,
    "movementCost": 999,
    "targetCost": 999,
    "layer": 2,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Floor Only",
      "No Destruct"
    ],
    "relatedDataType": 0,
    "relatedDataId": -1,
    "f3Distribution": {
      "0": 384
    },
    "f4Distribution": {
      "1": 384
    }
  },
  "54": {
    "chipId": 54,
    "semanticGroup": "unknown",
    "type": 24,
    "category": 39,
    "movementCost": 999,
    "targetCost": 999,
    "layer": 2,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Floor Only",
      "No Destruct"
    ],
    "relatedDataType": 0,
    "relatedDataId": -1,
    "f3Distribution": {
      "0": 279
    },
    "f4Distribution": {
      "1": 279
    }
  },
  "55": {
    "chipId": 55,
    "semanticGroup": "unknown",
    "type": 5,
    "category": 2,
    "movementCost": 5,
    "targetCost": 5,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "No Destruct",
      "Wall Place"
    ],
    "relatedDataType": 1,
    "relatedDataId": 63,
    "f3Distribution": {
      "0": 307
    },
    "f4Distribution": {
      "1": 307
    }
  },
  "56": {
    "chipId": 56,
    "semanticGroup": "unknown",
    "type": 5,
    "category": 2,
    "movementCost": 5,
    "targetCost": 5,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "No Destruct",
      "Wall Place"
    ],
    "relatedDataType": 1,
    "relatedDataId": 15,
    "f3Distribution": {
      "0": 377
    },
    "f4Distribution": {
      "1": 377
    }
  },
  "57": {
    "chipId": 57,
    "semanticGroup": "unknown",
    "type": 21,
    "category": 20,
    "movementCost": 0,
    "targetCost": 0,
    "layer": 1,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Ambient No Effect",
      "Floor Only",
      "No Construction",
      "Selectable"
    ],
    "relatedDataType": 1,
    "relatedDataId": 16,
    "f3Distribution": {
      "0": 264
    },
    "f4Distribution": {
      "1": 264
    }
  },
  "58": {
    "chipId": 58,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 35,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 1,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "Attack Target",
      "Mining",
      "No Construction",
      "No Destruct",
      "Out Territory OK",
      "Parameter",
      "Placable",
      "Selectable",
      "Terrain Only",
      "Walking Height Ignore"
    ],
    "relatedDataType": 1,
    "relatedDataId": 17,
    "f3Distribution": {
      "0": 305
    },
    "f4Distribution": {
      "1": 305
    }
  },
  "59": {
    "chipId": 59,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 42,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 1,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Construction",
      "No Destruct",
      "Walking Height Ignore"
    ],
    "relatedDataType": 1,
    "relatedDataId": 18,
    "f3Distribution": {
      "0": 427
    },
    "f4Distribution": {
      "1": 427
    }
  },
  "60": {
    "chipId": 60,
    "semanticGroup": "special overlay/runtime-marker",
    "type": 25,
    "category": 40,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 1,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "No Construction",
      "No Destruct",
      "Sync Animation",
      "Walking Height Ignore"
    ],
    "relatedDataType": 1,
    "relatedDataId": 19,
    "f3Distribution": {
      "0": 339
    },
    "f4Distribution": {
      "1": 339
    }
  },
  "61": {
    "chipId": 61,
    "semanticGroup": "unknown",
    "type": 13,
    "category": 52,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "No Construction",
      "No Destruct",
      "Out Territory OK"
    ],
    "relatedDataType": 0,
    "relatedDataId": -1,
    "f3Distribution": {
      "0": 257
    },
    "f4Distribution": {
      "1": 257
    }
  },
  "62": {
    "chipId": 62,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 36,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 1,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Construction",
      "No Destruct",
      "Parameter",
      "Terrain Only",
      "Walking Height Ignore"
    ],
    "relatedDataType": 1,
    "relatedDataId": 20,
    "f3Distribution": {
      "0": 252
    },
    "f4Distribution": {
      "1": 252
    }
  },
  "63": {
    "chipId": 63,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 43,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 1,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Construction",
      "No Destruct",
      "Walking Height Ignore"
    ],
    "relatedDataType": 1,
    "relatedDataId": 21,
    "f3Distribution": {
      "0": 371
    },
    "f4Distribution": {
      "1": 371
    }
  },
  "64": {
    "chipId": 64,
    "semanticGroup": "special overlay/runtime-marker",
    "type": 25,
    "category": 40,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 1,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "No Construction",
      "No Destruct",
      "Sync Animation",
      "Walking Height Ignore"
    ],
    "relatedDataType": 1,
    "relatedDataId": 22,
    "f3Distribution": {
      "0": 269
    },
    "f4Distribution": {
      "1": 269
    }
  },
  "65": {
    "chipId": 65,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 51,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 2,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Construction",
      "No Destruct"
    ],
    "relatedDataType": 0,
    "relatedDataId": -1,
    "f3Distribution": {
      "0": 202
    },
    "f4Distribution": {
      "1": 202
    }
  },
  "66": {
    "chipId": 66,
    "semanticGroup": "terrain/ground/water",
    "type": 17,
    "category": 48,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 2,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Attack Target",
      "Parameter",
      "Placable",
      "Selectable",
      "Water Only"
    ],
    "relatedDataType": 1,
    "relatedDataId": 66,
    "f3Distribution": {
      "0": 139
    },
    "f4Distribution": {
      "1": 139
    }
  },
  "67": {
    "chipId": 67,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 33,
    "movementCost": 5,
    "targetCost": 5,
    "layer": 2,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Destruct",
      "Selectable",
      "Terrain Only",
      "Walking Height Ignore"
    ],
    "relatedDataType": 1,
    "relatedDataId": 7,
    "f3Distribution": {
      "0": 168
    },
    "f4Distribution": {
      "1": 168
    }
  },
  "69": {
    "chipId": 69,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 33,
    "movementCost": 5,
    "targetCost": 5,
    "layer": 2,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Destruct",
      "Selectable",
      "Terrain Only",
      "Walking Height Ignore"
    ],
    "relatedDataType": 1,
    "relatedDataId": 9,
    "f3Distribution": {
      "0": 685
    },
    "f4Distribution": {
      "1": 685
    }
  },
  "70": {
    "chipId": 70,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 33,
    "movementCost": 5,
    "targetCost": 5,
    "layer": 2,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Destruct",
      "Selectable",
      "Terrain Only",
      "Walking Height Ignore"
    ],
    "relatedDataType": 1,
    "relatedDataId": 10,
    "f3Distribution": {
      "0": 631
    },
    "f4Distribution": {
      "1": 631
    }
  },
  "71": {
    "chipId": 71,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 34,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 2,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Construction",
      "No Destruct",
      "Out Territory OK",
      "Parameter",
      "Selectable",
      "Terrain Only",
      "Walking Height Ignore"
    ],
    "relatedDataType": 2,
    "relatedDataId": 96,
    "f3Distribution": {
      "0": 135
    },
    "f4Distribution": {
      "1": 135
    }
  },
  "72": {
    "chipId": 72,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 34,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 2,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Construction",
      "No Destruct",
      "Out Territory OK",
      "Parameter",
      "Selectable",
      "Terrain Only",
      "Walking Height Ignore"
    ],
    "relatedDataType": 2,
    "relatedDataId": 95,
    "f3Distribution": {
      "0": 531
    },
    "f4Distribution": {
      "1": 531
    }
  },
  "73": {
    "chipId": 73,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 34,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 2,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Construction",
      "No Destruct",
      "Out Territory OK",
      "Parameter",
      "Selectable",
      "Terrain Only",
      "Walking Height Ignore"
    ],
    "relatedDataType": 2,
    "relatedDataId": 97,
    "f3Distribution": {
      "0": 300
    },
    "f4Distribution": {
      "1": 300
    }
  },
  "74": {
    "chipId": 74,
    "semanticGroup": "unknown",
    "type": 17,
    "category": 34,
    "movementCost": 50,
    "targetCost": 50,
    "layer": 2,
    "sizeWidth": 2,
    "sizeHeight": 2,
    "flags": [
      "No Construction",
      "No Destruct",
      "Out Territory OK",
      "Parameter",
      "Selectable",
      "Terrain Only",
      "Walking Height Ignore"
    ],
    "relatedDataType": 2,
    "relatedDataId": 98,
    "f3Distribution": {
      "0": 744
    },
    "f4Distribution": {
      "1": 744
    }
  },
  "91": {
    "chipId": 91,
    "semanticGroup": "unknown",
    "type": 19,
    "category": 17,
    "movementCost": 100,
    "targetCost": 100,
    "layer": 0,
    "sizeWidth": 1,
    "sizeHeight": 1,
    "flags": [
      "Area Merge",
      "Attack Target",
      "Parameter",
      "Placable",
      "Selectable",
      "Soil Only",
      "Terrain Only",
      "Wall Place"
    ],
    "relatedDataType": 1,
    "relatedDataId": 40,
    "f3Distribution": {
      "0": 673
    },
    "f4Distribution": {
      "1": 673
    }
  }
};

const UNKNOWN_GROUP: F2SemanticGroup = "unknown";

export function getF2SemanticGroup(chipId: number): F2SemanticGroup {
  return F2_RUNTIME_META_BY_ID[chipId]?.semanticGroup ?? UNKNOWN_GROUP;
}

export function isF2RoadLike(chipId: number): boolean {
  return getF2SemanticGroup(chipId) === "road/path/traffic/buildable-related";
}

export function isF2TerrainLike(chipId: number): boolean {
  return getF2SemanticGroup(chipId) === "terrain/ground/water";
}

export function isF2SpecialOverlay(chipId: number): boolean {
  return getF2SemanticGroup(chipId) === "special overlay/runtime-marker";
}

export function getF2MapChipRuntimeMeta(chipId: number): F2MapChipRuntimeMeta | null {
  return F2_RUNTIME_META_BY_ID[chipId] ?? null;
}

