import { EQUIPMENT_CATALOG } from "@/lib/generated-equipment-data";

export type Weekday =
  | "Sunday"
  | "Monday"
  | "Tuesday"
  | "Wednesday"
  | "Thursday"
  | "Friday"
  | "Saturday";

export type RankLabel = "F" | "E" | "D" | "C" | "B" | "A" | "S";

export type DailyRankRewardTier = {
  rankValue: number;
  rankLabel: RankLabel;
  sourceRowId: number;
  weapon: string;
  armor: string;
  shield: string;
  overallItem1: string;
  overallItem2: string;
  ticket: string;
  skill: string;
};

export type DailyRankRewardDay = {
  day: Weekday;
  rewards: DailyRankRewardTier[];
};

type RawTreasureRankRow = Omit<DailyRankRewardTier, "rankLabel"> & {
  dayIndex: number;
};

const DISPLAY_WEEKDAYS: Weekday[] = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

const SOURCE_DAY_INDEX_BY_WEEKDAY: Record<Weekday, number> = {
  Sunday: 0,
  Monday: 1,
  Tuesday: 2,
  Wednesday: 3,
  Thursday: 4,
  Friday: 5,
  Saturday: 6,
};

const RANK_LABEL_BY_VALUE: RankLabel[] = ["F", "E", "D", "C", "B", "A", "S"];

const RAW_TREASURE_RANK_ROWS: RawTreasureRankRow[] = [
  {
    dayIndex: 0,
    rankValue: 0,
    sourceRowId: 548,
    weapon: "E/ Sword",
    armor: "",
    shield: "",
    overallItem1: "Skill Slots Up",
    overallItem2: "Bounty Bag",
    ticket: "Grass Pouch",
    skill: "Parry",
  },
  {
    dayIndex: 0,
    rankValue: 1,
    sourceRowId: 549,
    weapon: "E/ Sword",
    armor: "",
    shield: "",
    overallItem1: "Skill Slots Up",
    overallItem2: "Bounty Bag",
    ticket: "Wood Pouch",
    skill: "Parry",
  },
  {
    dayIndex: 0,
    rankValue: 2,
    sourceRowId: 550,
    weapon: "D/ Steel Sword",
    armor: "F/ Loincloth",
    shield: "",
    overallItem1: "Skill Slots Up",
    overallItem2: "2x Bounty Bag",
    ticket: "Food Pouch",
    skill: "2-Hit Attack",
  },
  {
    dayIndex: 0,
    rankValue: 3,
    sourceRowId: 551,
    weapon: "D/ Steel Sword",
    armor: "F/ Linen Garment",
    shield: "",
    overallItem1: "Skill Slots Up",
    overallItem2: "2x Bounty Bag",
    ticket: "Iron Pouch",
    skill: "Thief",
  },
  {
    dayIndex: 0,
    rankValue: 4,
    sourceRowId: 552,
    weapon: "C/ Master's Sword",
    armor: "E/ Durable Garment",
    shield: "F/ Wooden Shield",
    overallItem1: "Skill Slots Up",
    overallItem2: "3x Bounty Bag",
    ticket: "Magic Pouch",
    skill: "3-Hit Attack",
  },
  {
    dayIndex: 0,
    rankValue: 5,
    sourceRowId: 553,
    weapon: "B/ Commander's Sword",
    armor: "D/ Thick Garment",
    shield: "D/ Iron Shield",
    overallItem1: "2x Skill Slots Up",
    overallItem2: "3x Bounty Bag",
    ticket: "Facility Trade Ticket",
    skill: "4-Hit Attack",
  },
  {
    dayIndex: 0,
    rankValue: 6,
    sourceRowId: 554,
    weapon: "A/ Artisanal Sword",
    armor: "C/ Skirt",
    shield: "C/ Demonic Shield",
    overallItem1: "3x Skill Slots Up",
    overallItem2: "Eternal Candle",
    ticket: "Facility Trade Ticket",
    skill: "5-Hit Attack",
  },
  {
    dayIndex: 1,
    rankValue: 0,
    sourceRowId: 555,
    weapon: "E/ Gnarly Club",
    armor: "",
    shield: "",
    overallItem1: "Holy Herb",
    overallItem2: "Running Shoes",
    ticket: "Grass Pouch",
    skill: "Spear Resistance",
  },
  {
    dayIndex: 1,
    rankValue: 1,
    sourceRowId: 556,
    weapon: "E/ Gnarly Club",
    armor: "",
    shield: "",
    overallItem1: "2x Holy Herb",
    overallItem2: "Running Shoes",
    ticket: "Wood Pouch",
    skill: "Spear Resistance",
  },
  {
    dayIndex: 1,
    rankValue: 2,
    sourceRowId: 557,
    weapon: "D/ Ladle",
    armor: "F/ Loincloth",
    shield: "",
    overallItem1: "2x Holy Herb",
    overallItem2: "2x Running Shoes",
    ticket: "Food Pouch",
    skill: "Lightning Magic I",
  },
  {
    dayIndex: 1,
    rankValue: 3,
    sourceRowId: 558,
    weapon: "D/ Ladle",
    armor: "E/ Yellow Garment",
    shield: "",
    overallItem1: "3x Holy Herb",
    overallItem2: "2x Running Shoes",
    ticket: "Iron Pouch",
    skill: "Lightning Magic II",
  },
  {
    dayIndex: 1,
    rankValue: 4,
    sourceRowId: 559,
    weapon: "C/ Club",
    armor: "D/ Chain Mail",
    shield: "E/ Infantry Shield",
    overallItem1: "Recovery Potion (L)",
    overallItem2: "3x Running Shoes",
    ticket: "Magic Pouch",
    skill: "Lightning Magic III",
  },
  {
    dayIndex: 1,
    rankValue: 5,
    sourceRowId: 560,
    weapon: "B/ Iron Club",
    armor: "C/ Durable Cape",
    shield: "D/ Folk Art Shield",
    overallItem1: "2x Recovery Potion (L)",
    overallItem2: "3x Running Shoes",
    ticket: "Job Trade Ticket",
    skill: "Lightning Magic IV",
  },
  {
    dayIndex: 1,
    rankValue: 6,
    sourceRowId: 561,
    weapon: "A/ Red Club",
    armor: "B/ Purple Cape",
    shield: "B/ Green Shield",
    overallItem1: "3x Recovery Potion (L)",
    overallItem2: "Eternal Candle",
    ticket: "Job Trade Ticket",
    skill: "Lightning Magic V",
  },
  {
    dayIndex: 2,
    rankValue: 0,
    sourceRowId: 562,
    weapon: "F/ Bludgeon",
    armor: "",
    shield: "",
    overallItem1: "Energizing Stew",
    overallItem2: "Homeopathic Elixir",
    ticket: "Grass Pouch",
    skill: "Book Resistance",
  },
  {
    dayIndex: 2,
    rankValue: 1,
    sourceRowId: 563,
    weapon: "F/ Bludgeon",
    armor: "",
    shield: "",
    overallItem1: "2x Energizing Stew",
    overallItem2: "Homeopathic Elixir",
    ticket: "Wood Pouch",
    skill: "Book Resistance",
  },
  {
    dayIndex: 2,
    rankValue: 2,
    sourceRowId: 564,
    weapon: "E/ Tough Club",
    armor: "D/ Pajamas",
    shield: "",
    overallItem1: "2x Energizing Stew",
    overallItem2: "2x Homeopathic Elixir",
    ticket: "Food Pouch",
    skill: "Ice Magic I",
  },
  {
    dayIndex: 2,
    rankValue: 3,
    sourceRowId: 565,
    weapon: "E/ Tough Club",
    armor: "D/ Iron Chest Guard",
    shield: "",
    overallItem1: "3x Energizing Stew",
    overallItem2: "2x Homeopathic Elixir",
    ticket: "Iron Pouch",
    skill: "Ice Magic II",
  },
  {
    dayIndex: 2,
    rankValue: 4,
    sourceRowId: 566,
    weapon: "D/ The Spike",
    armor: "C/ Leather Armor",
    shield: "F/ Leather Shield",
    overallItem1: "Skill Slots Up",
    overallItem2: "3x Homeopathic Elixir",
    ticket: "Magic Pouch",
    skill: "Ice Magic III",
  },
  {
    dayIndex: 2,
    rankValue: 5,
    sourceRowId: 567,
    weapon: "C/ Artistic Club",
    armor: "C/ Light Mail",
    shield: "D/ Sturdy Shield",
    overallItem1: "2x Skill Slots Up",
    overallItem2: "3x Homeopathic Elixir",
    ticket: "Equipment Trade Ticket",
    skill: "Ice Magic IV",
  },
  {
    dayIndex: 2,
    rankValue: 6,
    sourceRowId: 568,
    weapon: "A/ Emerald Club",
    armor: "B/ Bronze Armor",
    shield: "C/ Nightmare Shield",
    overallItem1: "3x Skill Slots Up",
    overallItem2: "Eternal Candle",
    ticket: "Equipment Trade Ticket",
    skill: "Ice Magic V",
  },
  {
    dayIndex: 3,
    rankValue: 0,
    sourceRowId: 569,
    weapon: "F/ Iron Staff",
    armor: "",
    shield: "",
    overallItem1: "Holy Herb",
    overallItem2: "Recover Energy",
    ticket: "Grass Pouch",
    skill: "Club Resistance",
  },
  {
    dayIndex: 3,
    rankValue: 1,
    sourceRowId: 570,
    weapon: "F/ Iron Staff",
    armor: "",
    shield: "",
    overallItem1: "2x Holy Herb",
    overallItem2: "Recover Energy",
    ticket: "Wood Pouch",
    skill: "Facility Rec. UP Vigor",
  },
  {
    dayIndex: 3,
    rankValue: 2,
    sourceRowId: 571,
    weapon: "E/ Wooden Wand",
    armor: "F/ Loincloth",
    shield: "",
    overallItem1: "2x Holy Herb",
    overallItem2: "2x Recover Energy",
    ticket: "Food Pouch",
    skill: "Fire Magic I",
  },
  {
    dayIndex: 3,
    rankValue: 3,
    sourceRowId: 572,
    weapon: "E/ Wooden Wand",
    armor: "F/ Linen Garment",
    shield: "",
    overallItem1: "3x Holy Herb",
    overallItem2: "2x Recover Energy",
    ticket: "Iron Pouch",
    skill: "Fire Magic II",
  },
  {
    dayIndex: 3,
    rankValue: 4,
    sourceRowId: 573,
    weapon: "C/ Spiked Staff",
    armor: "E/ Durable Garment",
    shield: "E/ Buckler",
    overallItem1: "Recovery Potion (L)",
    overallItem2: "3x Recover Energy",
    ticket: "Magic Pouch",
    skill: "Fire Magic III",
  },
  {
    dayIndex: 3,
    rankValue: 5,
    sourceRowId: 574,
    weapon: "B/ Shining Staff",
    armor: "D/ Thick Garment",
    shield: "D/ Folk Art Shield",
    overallItem1: "2x Recovery Potion (L)",
    overallItem2: "3x Recover Energy",
    ticket: "Item Trade Ticket",
    skill: "Fire Magic IV",
  },
  {
    dayIndex: 3,
    rankValue: 6,
    sourceRowId: 575,
    weapon: "A/ Light Staff",
    armor: "C/ Skirt",
    shield: "B/ Shell Shield",
    overallItem1: "3x Recovery Potion (L)",
    overallItem2: "Eternal Candle",
    ticket: "Item Trade Ticket",
    skill: "Fire Magic V",
  },
  {
    dayIndex: 4,
    rankValue: 0,
    sourceRowId: 576,
    weapon: "E/ Kunai",
    armor: "",
    shield: "",
    overallItem1: "Energizing Stew",
    overallItem2: "Mystic Flute",
    ticket: "Grass Pouch",
    skill: "Hammer Resistance",
  },
  {
    dayIndex: 4,
    rankValue: 1,
    sourceRowId: 577,
    weapon: "E/ Kunai",
    armor: "",
    shield: "",
    overallItem1: "2x Energizing Stew",
    overallItem2: "Mystic Flute",
    ticket: "Wood Pouch",
    skill: "Hammer Resistance",
  },
  {
    dayIndex: 4,
    rankValue: 2,
    sourceRowId: 578,
    weapon: "D/ Ninja Star",
    armor: "F/ Loincloth",
    shield: "",
    overallItem1: "2x Energizing Stew",
    overallItem2: "2x Mystic Flute",
    ticket: "Food Pouch",
    skill: "Move Speed UP",
  },
  {
    dayIndex: 4,
    rankValue: 3,
    sourceRowId: 579,
    weapon: "D/ Ninja Star",
    armor: "E/ Yellow Garment",
    shield: "",
    overallItem1: "3x Energizing Stew",
    overallItem2: "2x Mystic Flute",
    ticket: "Iron Pouch",
    skill: "Area Attack I",
  },
  {
    dayIndex: 4,
    rankValue: 4,
    sourceRowId: 580,
    weapon: "C/ Giant Ninja Star",
    armor: "D/ Chain Mail",
    shield: "D/ Iron Shield",
    overallItem1: "Skill Slots Up",
    overallItem2: "3x Mystic Flute",
    ticket: "Magic Pouch",
    skill: "Area Attack II",
  },
  {
    dayIndex: 4,
    rankValue: 5,
    sourceRowId: 581,
    weapon: "B/ Flame Ninja Star",
    armor: "C/ Durable Cape",
    shield: "C/ Nightmare Shield",
    overallItem1: "2x Skill Slots Up",
    overallItem2: "3x Mystic Flute",
    ticket: "Facility Trade Ticket",
    skill: "Stealth",
  },
  {
    dayIndex: 4,
    rankValue: 6,
    sourceRowId: 582,
    weapon: "A/ Giga Ninja Star",
    armor: "B/ Purple Cape",
    shield: "B/ Green Shield",
    overallItem1: "3x Skill Slots Up",
    overallItem2: "Eternal Candle",
    ticket: "Facility Trade Ticket",
    skill: "Area Attack III",
  },
  {
    dayIndex: 5,
    rankValue: 0,
    sourceRowId: 583,
    weapon: "F/ Bronze Sword",
    armor: "",
    shield: "",
    overallItem1: "Energizing Stew",
    overallItem2: "Holy Herb",
    ticket: "Grass Pouch",
    skill: "Axe Resistance",
  },
  {
    dayIndex: 5,
    rankValue: 1,
    sourceRowId: 584,
    weapon: "F/ Bronze Sword",
    armor: "",
    shield: "",
    overallItem1: "2x Energizing Stew",
    overallItem2: "Holy Herb",
    ticket: "Wood Pouch",
    skill: "Auto Recovery Vigor",
  },
  {
    dayIndex: 5,
    rankValue: 2,
    sourceRowId: 585,
    weapon: "E/ Copper Sword",
    armor: "D/ Pajamas",
    shield: "",
    overallItem1: "2x Energizing Stew",
    overallItem2: "2x Holy Herb",
    ticket: "Food Pouch",
    skill: "Direct Attack I",
  },
  {
    dayIndex: 5,
    rankValue: 3,
    sourceRowId: 586,
    weapon: "E/ Copper Sword",
    armor: "D/ Iron Chest Guard",
    shield: "",
    overallItem1: "3x Energizing Stew",
    overallItem2: "2x Holy Herb",
    ticket: "Iron Pouch",
    skill: "Direct Attack I",
  },
  {
    dayIndex: 5,
    rankValue: 4,
    sourceRowId: 587,
    weapon: "C/ Tempered Sword",
    armor: "C/ Leather Armor",
    shield: "D/ Iron Shield",
    overallItem1: "Recovery Potion (L)",
    overallItem2: "3x Holy Herb",
    ticket: "Magic Pouch",
    skill: "Direct Attack II",
  },
  {
    dayIndex: 5,
    rankValue: 5,
    sourceRowId: 588,
    weapon: "B/ Lightweight Sword",
    armor: "C/ Light Mail",
    shield: "C/ Noble Shield",
    overallItem1: "2x Recovery Potion (L)",
    overallItem2: "3x Holy Herb",
    ticket: "Equipment Trade Ticket",
    skill: "Experience UP II",
  },
  {
    dayIndex: 5,
    rankValue: 6,
    sourceRowId: 589,
    weapon: "A/ Honor Sword",
    armor: "B/ Bronze Armor",
    shield: "B/ Scholar's Shield",
    overallItem1: "3x Recovery Potion (L)",
    overallItem2: "Eternal Candle",
    ticket: "Equipment Trade Ticket",
    skill: "Experience UP III",
  },
  {
    dayIndex: 6,
    rankValue: 0,
    sourceRowId: 590,
    weapon: "D/ Bow",
    armor: "",
    shield: "",
    overallItem1: "Skill Slots Up",
    overallItem2: "Energizing Stew",
    ticket: "Grass Pouch",
    skill: "Staff Resistance",
  },
  {
    dayIndex: 6,
    rankValue: 1,
    sourceRowId: 591,
    weapon: "D/ Bow",
    armor: "",
    shield: "",
    overallItem1: "Skill Slots Up",
    overallItem2: "Energizing Stew",
    ticket: "Wood Pouch",
    skill: "Deployment Range I",
  },
  {
    dayIndex: 6,
    rankValue: 2,
    sourceRowId: 592,
    weapon: "C/ Infantry Bow",
    armor: "D/ Pajamas",
    shield: "",
    overallItem1: "Skill Slots Up",
    overallItem2: "2x Energizing Stew",
    ticket: "Food Pouch",
    skill: "Heal Maddy",
  },
  {
    dayIndex: 6,
    rankValue: 3,
    sourceRowId: 593,
    weapon: "C/ Infantry Bow",
    armor: "D/ Iron Chest Guard",
    shield: "",
    overallItem1: "Skill Slots Up",
    overallItem2: "2x Energizing Stew",
    ticket: "Iron Pouch",
    skill: "Heal M",
  },
  {
    dayIndex: 6,
    rankValue: 4,
    sourceRowId: 594,
    weapon: "C/ Infantry Bow",
    armor: "C/ Leather Armor",
    shield: "D/ Iron Shield",
    overallItem1: "Skill Slots Up",
    overallItem2: "3x Energizing Stew",
    ticket: "Magic Pouch",
    skill: "Deployment Range II",
  },
  {
    dayIndex: 6,
    rankValue: 5,
    sourceRowId: 595,
    weapon: "B/ Hunting Bow",
    armor: "C/ Light Mail",
    shield: "C/ Nightmare Shield",
    overallItem1: "2x Skill Slots Up",
    overallItem2: "3x Energizing Stew",
    ticket: "Item Trade Ticket",
    skill: "Heal L",
  },
  {
    dayIndex: 6,
    rankValue: 6,
    sourceRowId: 596,
    weapon: "A/ Swift Bow",
    armor: "B/ Bronze Armor",
    shield: "B/ Green Shield",
    overallItem1: "3x Skill Slots Up",
    overallItem2: "Eternal Candle",
    ticket: "Item Trade Ticket",
    skill: "Stubborn",
  }
];

export const DAILY_RANK_REWARDS: DailyRankRewardDay[] = DISPLAY_WEEKDAYS.map((day) => {
  const sourceDayIndex = SOURCE_DAY_INDEX_BY_WEEKDAY[day];
  const rewards = RAW_TREASURE_RANK_ROWS
    .filter((row) => row.dayIndex === sourceDayIndex)
    .map((row) => ({
      rankValue: row.rankValue,
      rankLabel: RANK_LABEL_BY_VALUE[row.rankValue] ?? "F",
      sourceRowId: row.sourceRowId,
      weapon: row.weapon,
      armor: row.armor,
      shield: row.shield,
      overallItem1: row.overallItem1,
      overallItem2: row.overallItem2,
      ticket: row.ticket,
      skill: row.skill,
    }))
    .sort((a, b) => b.rankValue - a.rankValue);

  return { day, rewards };
});

const EQUIPMENT_NAME_SET = new Set<string>(
  EQUIPMENT_CATALOG.map((entry) => (entry as { name?: string }).name ?? "").filter(Boolean),
);

export type DailyRankEquipmentMismatch = {
  day: Weekday;
  rankLabel: RankLabel;
  slot: "weapon" | "armor" | "shield";
  value: string;
  sourceRowId: number;
};

export function getDailyRankEquipmentMismatches(): DailyRankEquipmentMismatch[] {
  const mismatches: DailyRankEquipmentMismatch[] = [];

  for (const day of DAILY_RANK_REWARDS) {
    for (const reward of day.rewards) {
      for (const slot of ["weapon", "armor", "shield"] as const) {
        const value = reward[slot]?.trim();
        if (!value) {
          continue;
        }
        if (!EQUIPMENT_NAME_SET.has(value)) {
          mismatches.push({
            day: day.day,
            rankLabel: reward.rankLabel,
            slot,
            value,
            sourceRowId: reward.sourceRowId,
          });
        }
      }
    }
  }

  return mismatches;
}
