// -- Data (from KA GameData facility sources) ---------------------------------

export type FacilityTab = "env" | "materials" | "amenity" | "indoors" | "map";

export const FACILITY_TABS: { key: FacilityTab; label: string }[] = [
  { key: "env",       label: "Env." },
  { key: "materials", label: "Materials" },
  { key: "amenity",   label: "Amenity" },
  { key: "indoors",   label: "Indoors" },
  { key: "map",       label: "Map" },
];

export interface Facility {
  id: number;
  name: string;
  tab: FacilityTab;
  size: string;        // e.g. "1×1", "2×2", "4×4", "1×2"
  rotatable?: boolean; // true if size is not square and can be rotated
  mapUnlock?: number;  // map tile level required to unlock (map-tab facilities only)
  // Build costs: min = level 1, max = max level (0 = unknown)
  minGrass: number; minWood: number; minFood: number; minOre: number; minMystic: number;
  maxGrass: number; maxWood: number; maxFood: number; maxOre: number; maxMystic: number;
  minHp: number;       // 0 = unknown
  maxHp: number;
  validRange: number;  // territory expansion radius in tiles (0 = none)
  canUpgrade: boolean;
  // Upgrade costs: lv 1?2 (min) and lv max-1?max (max). All 0 if not upgradeable.
  upgGrass: number; upgWood: number; upgFood: number; upgOre: number; upgMystic: number;
  maxUpgGrass: number; maxUpgWood: number; maxUpgFood: number; maxUpgOre: number; maxUpgMystic: number;
  // Harvest count (Field/Plantation only): how many times you can harvest per planting
  minUseCount?: number; maxUseCount?: number;
}

export const FACILITIES: Facility[] = [
  // -- Env. ------------------------------------------------------------------
  { id: 17,  name: "Town Hall",                tab: "env",  size: "4×4",
    minGrass:  0, minWood:  0, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  1, upgWood:  1, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 150, maxUpgWood: 300, maxUpgFood: 100, maxUpgOre:  50, maxUpgMystic: 15,
    minHp: 50, maxHp: 500, validRange: 15, canUpgrade: true },
  // Walls
  { id: 23,  name: "Fence",                    tab: "env",  size: "",
    minGrass:  1, minWood:  0, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass: 10, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  1, upgWood:  0, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 80, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 15, maxHp: 315, validRange:  0, canUpgrade: true },
  { id: 24,  name: "Wood Wall",                tab: "env",  size: "",
    minGrass:  0, minWood:  2, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood: 18, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  2, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 40, maxHp: 430, validRange:  0, canUpgrade: true },
  { id: 25,  name: "Defensive Wall",           tab: "env",  size: "",
    minGrass:  0, minWood:  2, minFood:  0, minOre:  2, minMystic:  0,
    maxGrass:  0, maxWood: 18, maxFood:  0, maxOre: 14, maxMystic:  0,
    upgGrass:  0, upgWood:  2, upgFood:  0, upgOre:  2, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 65, maxUpgMystic: 8,
    minHp: 65, maxHp: 650, validRange:  0, canUpgrade: true },
  { id: 26,  name: "Castle Wall",              tab: "env",  size: "",
    minGrass:  0, minWood:  0, minFood:  0, minOre:  3, minMystic:  1,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre: 21, maxMystic:  6,
    upgGrass:  0, upgWood:  0, upgFood:  0, upgOre:  3, upgMystic:  1,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 70, maxUpgMystic: 50,
    minHp: 90, maxHp: 975, validRange:  0, canUpgrade: true },
  { id: 28,  name: "Gate",                     tab: "env",  size: "1×2",  rotatable: true,
    minGrass:  1, minWood:  3, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass: 10, maxWood: 27, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  1, upgWood:  3, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 80, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 25, maxHp: 600, validRange:  0, canUpgrade: true },
  // Territory expansion
  { id: 29,  name: "Torch",                    tab: "env",  size: "",
    minGrass:  0, minWood:  3, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood: 27, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  3, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  7, canUpgrade: true },
  { id: 30,  name: "Nighttime Meeting Place",  tab: "env",  size: "",
    minGrass:  3, minWood:  4, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass: 30, maxWood: 36, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  3, upgWood:  4, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 90, maxUpgWood: 90, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  8, canUpgrade: true },
  { id: 31,  name: "Low Watchtower",           tab: "env",  size: "",
    minGrass:  5, minWood:  8, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass: 50, maxWood: 72, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  5, upgWood:  8, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 100, maxUpgWood: 110, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange: 10, canUpgrade: true },
  { id: 32,  name: "Turret",                   tab: "env",  size: "2×2",
    minGrass:  7, minWood: 11, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass: 70, maxWood: 99, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  7, upgWood: 11, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 110, maxUpgWood: 125, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange: 12, canUpgrade: true },
  // Outdoor utility
  { id: 68,  name: "Info Board",               tab: "amenity",  size: "",
    minGrass:  0, minWood:  2, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  0, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass:  0, maxUpgWood:  0, maxUpgFood:  0, maxUpgOre:  0, maxUpgMystic:  0,
    minHp:  0, maxHp:   0, validRange: 10, canUpgrade: false },

  { id: 41 , name: "Canal",                         tab: "env",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 10, maxHp: 510, validRange: 0, canUpgrade: true },
  { id: 191, name: "Chaos Stone",                  tab: "env",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: false },
  { id: 76 , name: "Simple Stove",                  tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 1, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 75, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 77 , name: "Bonfire",                       tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 2, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 78 , name: "Thorny Trap",                   tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 2, upgOre: 1, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 70, maxUpgOre: 60, maxUpgMystic: 8,
    minHp: 15, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 79 , name: "Flowerbed",                     tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 80 , name: "Bushes",                        tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 2, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 85, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 81 , name: "Seedlings",                     tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 3, upgWood: 2, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 90, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 82 , name: "Fountain",                      tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 2, upgMystic: 3,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 65, maxUpgMystic: 60,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 83 , name: "Goddess Statue",                tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 3, upgMystic: 5,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 70, maxUpgMystic: 70,
    minHp: 10, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 84 , name: "Rejuvenation Spring",           tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 5, upgMystic: 3,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 80, maxUpgMystic: 60,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 85 , name: "Monster Statue",                tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 2, upgFood: 0, upgOre: 0, upgMystic: 5,
    maxUpgGrass: 15, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 70,
    minHp: 65, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 86 , name: "Monster-Repelling Orb",         tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 1, upgMystic: 2,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 60, maxUpgMystic: 55,
    minHp: 40, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 87 , name: "Monster-Repelling Sword",       tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 1, upgMystic: 3,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 60, maxUpgMystic: 60,
    minHp: 55, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 88 , name: "Monster-Repelling Slate",       tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 1, upgMystic: 5,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 60, maxUpgMystic: 70,
    minHp: 70, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 89 , name: "Windmill",                      tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 10, upgFood: 0, upgOre: 10, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 120, maxUpgFood: 12, maxUpgOre: 105, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 91 , name: "Bench",                         tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 2, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 164, name: "Recovery Outpost",              tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },

  // -- Materials -------------------------------------------------------------
  // Standard storehouses
  { id: 33,  name: "Grass Storehouse",         tab: "materials",  size: "2×2",
    minGrass:  2, minWood:  0, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass: 20, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  2, upgWood:  0, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 85, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 35,  name: "Wood Storehouse",          tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  2, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood: 18, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  2, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 34,  name: "Food Storehouse",          tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  0, minFood:  2, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood:  0, maxFood: 16, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  0, upgFood:  2, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 70, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 36,  name: "Ore Storehouse",           tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  0, minFood:  0, minOre:  2, minMystic:  0,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre: 14, maxMystic:  0,
    upgGrass:  0, upgWood:  0, upgFood:  0, upgOre:  2, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 65, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 37,  name: "Mystic Ore Storehouse",    tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  0, minFood:  0, minOre:  0, minMystic:  2,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic: 12,
    upgGrass:  0, upgWood:  0, upgFood:  0, upgOre:  0, upgMystic:  2,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 55,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 38,  name: "Item Storehouse",          tab: "materials",  size: "2×2",
    minGrass:  2, minWood:  0, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass: 20, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  2, upgWood:  0, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 85, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 39,  name: "Energy Storehouse",        tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  2, minFood:  1, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood: 18, maxFood:  8, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  2, upgFood:  1, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 80, maxUpgFood: 65, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 40,  name: "Treasure Storehouse",      tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  1, minFood:  0, minOre:  2, minMystic:  0,
    maxGrass:  0, maxWood:  9, maxFood:  0, maxOre: 14, maxMystic:  0,
    upgGrass:  0, upgWood:  1, upgFood:  0, upgOre:  2, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 75, maxUpgFood: 12, maxUpgOre: 65, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  // Coin storehouses
  { id: 183, name: "Copper Coin Storehouse",   tab: "materials",  size: "",
    minGrass:  0, minWood:  2, minFood:  0, minOre:  0, minMystic:  2,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  2, upgFood:  0, upgOre:  0, upgMystic:  2,
    maxUpgGrass: 15, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 55,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 184, name: "Silver Coin Storehouse",   tab: "materials",  size: "",
    minGrass:  0, minWood:  4, minFood:  0, minOre:  0, minMystic:  4,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  4, upgFood:  0, upgOre:  0, upgMystic:  4,
    maxUpgGrass: 15, maxUpgWood: 90, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 65,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  // High-grade storehouses
  { id: 206, name: "HG Grass Storehouse",      tab: "materials",  size: "2×2",
    minGrass:  2, minWood:  2, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass: 20, maxWood: 18, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  2, upgWood:  2, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 85, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 207, name: "HG Wood Storehouse",       tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  2, minFood:  2, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood: 18, maxFood: 16, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  2, upgFood:  2, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 80, maxUpgFood: 70, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 208, name: "HG Food Storehouse",       tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  0, minFood:  2, minOre:  2, minMystic:  0,
    maxGrass:  0, maxWood:  0, maxFood: 16, maxOre: 14, maxMystic:  0,
    upgGrass:  0, upgWood:  0, upgFood:  2, upgOre:  2, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 70, maxUpgOre: 65, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 209, name: "HG Ore Storehouse",        tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  0, minFood:  0, minOre:  2, minMystic:  2,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre: 14, maxMystic: 12,
    upgGrass:  0, upgWood:  0, upgFood:  0, upgOre:  2, upgMystic:  2,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 65, maxUpgMystic: 55,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 210, name: "HG Mystic Storehouse",     tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  0, minFood:  0, minOre:  0, minMystic:  2,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic: 12,
    upgGrass:  0, upgWood:  0, upgFood:  0, upgOre:  0, upgMystic:  2,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 55,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 211, name: "HG Energy Storehouse",     tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  0, minFood:  3, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood:  0, maxFood: 24, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  0, upgFood:  3, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 75, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 212, name: "HG Treasure Storehouse",   tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  0, minFood:  0, minOre:  2, minMystic:  2,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre: 14, maxMystic: 12,
    upgGrass:  0, upgWood:  0, upgFood:  0, upgOre:  2, upgMystic:  2,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 65, maxUpgMystic: 55,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 213, name: "HG Item Storehouse",       tab: "materials",  size: "2×2",
    minGrass:  3, minWood:  0, minFood:  0, minOre:  3, minMystic:  0,
    maxGrass: 30, maxWood:  0, maxFood:  0, maxOre: 21, maxMystic:  0,
    upgGrass:  3, upgWood:  0, upgFood:  0, upgOre:  3, upgMystic:  0,
    maxUpgGrass: 90, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 70, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 214, name: "HG Egg Storehouse",        tab: "materials",  size: "2×2",
    minGrass:  2, minWood:  0, minFood:  2, minOre:  0, minMystic:  0,
    maxGrass: 20, maxWood:  0, maxFood: 16, maxOre:  0, maxMystic:  0,
    upgGrass:  2, upgWood:  0, upgFood:  2, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 85, maxUpgWood: 14, maxUpgFood: 70, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  // Production
  { id: 42,  name: "Field",                    tab: "materials",  size: "2×2",
    minGrass:  1, minWood:  0, minFood:  2, minOre:  0, minMystic:  0,
    maxGrass: 10, maxWood:  0, maxFood: 16, maxOre:  0, maxMystic:  0,
    upgGrass:  1, upgWood:  0, upgFood:  2, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 80, maxUpgWood: 14, maxUpgFood: 70, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 10, maxHp: 510, validRange:  0, canUpgrade: true, minUseCount: 8, maxUseCount: 99 },
  { id: 43,  name: "Plantation",               tab: "materials",  size: "2×2",
    minGrass:  1, minWood:  3, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass: 10, maxWood: 27, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  1, upgWood:  3, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 80, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 10, maxHp: 510, validRange:  0, canUpgrade: true, minUseCount: 8, maxUseCount: 99 },
  { id: 44,  name: "Ranch",                    tab: "materials",  size: "2×2",
    minGrass:  5, minWood: 10, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass: 50, maxWood: 90, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  5, upgWood: 10, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 100, maxUpgWood: 120, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 10, maxHp: 510, validRange:  0, canUpgrade: true },
  { id: 45,  name: "Mine: Ore",                tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  3, minFood:  0, minOre:  5, minMystic:  0,
    maxGrass:  0, maxWood: 27, maxFood:  0, maxOre:  35, maxMystic:  0,
    upgGrass:  0, upgWood:  3, upgFood:  0, upgOre:  5, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 80, maxUpgMystic: 8,
    minHp: 10, maxHp: 510, validRange:  0, canUpgrade: true },
  { id: 46,  name: "Mine: Mystic Ore",         tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  0, minFood:  0, minOre:  5, minMystic:  8,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  35, maxMystic:  48,
    upgGrass:  0, upgWood:  0, upgFood:  0, upgOre:  5, upgMystic:  8,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 80, maxUpgMystic: 85,
    minHp: 10, maxHp: 510, validRange:  0, canUpgrade: true },
  { id: 47,  name: "Mine: Energy",             tab: "materials",  size: "2×2",
    minGrass:  0, minWood:  3, minFood:  5, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood: 27, maxFood: 40, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  3, upgFood:  5, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 15, maxUpgWood: 85, maxUpgFood: 85, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 20, maxHp: 520, validRange:  0, canUpgrade: true },
  { id: 194, name: "Egg House",                tab: "materials",  size: "2×2",
    minGrass:  2, minWood:  0, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  2, upgWood:  0, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 85, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },

  { id: 90 , name: "Monster Feed",                  tab: "materials",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 3, upgWood: 0, upgFood: 2, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 90, maxUpgWood: 14, maxUpgFood: 70, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  // -- Amenity ---------------------------------------------------------------
  { id: 67,  name: "Well",                     tab: "amenity",  size: "",
    minGrass:  1, minWood:  2, minFood:  0, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  1, upgWood:  2, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass: 80, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: true },
  { id: 70,  name: "Stables",                   tab: "amenity",  size: "",
    minGrass:  0, minWood:  5, minFood:  3, minOre:  0, minMystic:  0,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  0, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass:  0, maxUpgWood:  0, maxUpgFood:  0, maxUpgOre:  0, maxUpgMystic:  0,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: false },
  { id: 71,  name: "Wagon Yard",               tab: "amenity",  size: "",
    minGrass:  0, minWood:  2, minFood:  0, minOre:  1, minMystic:  0,
    maxGrass:  0, maxWood:  0, maxFood:  0, maxOre:  0, maxMystic:  0,
    upgGrass:  0, upgWood:  0, upgFood:  0, upgOre:  0, upgMystic:  0,
    maxUpgGrass:  0, maxUpgWood:  0, maxUpgFood:  0, maxUpgOre:  0, maxUpgMystic:  0,
    minHp:  0, maxHp:   0, validRange:  0, canUpgrade: false },

  { id: 69 , name: "Wasteland Guide",               tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 14, canUpgrade: true },
  { id: 72 , name: "Outdoor: Analysis Lab",          tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 74 , name: "Outdoor: Research Lab",          tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 75 , name: "Rest Stop",                     tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 3, upgFood: 0, upgOre: 1, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 60, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 92 , name: "Expedition Hut",                tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 3, upgFood: 5, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 85, maxUpgFood: 85, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 10, canUpgrade: true },
  { id: 102, name: "Register",                      tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 103, name: "Store Shelves",                 tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 3, maxHp: 50, validRange: 0, canUpgrade: true },
  { id: 104, name: "Skill Shelves",                 tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 3, maxHp: 50, validRange: 0, canUpgrade: true },
  { id: 105, name: "Furniture Shelves",             tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 3, maxHp: 50, validRange: 0, canUpgrade: true },
  { id: 132, name: "Training Room",                 tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 2, upgWood: 3, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 85, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 133, name: "Shooting Range",                tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 5, upgFood: 0, upgOre: 3, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 95, maxUpgFood: 12, maxUpgOre: 70, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 134, name: "Magic Training Ground",         tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 3, upgFood: 0, upgOre: 0, upgMystic: 5,
    maxUpgGrass: 15, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 70,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 157, name: "Monster Room",                  tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 160, name: "Dragon Stables",                tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 176, name: "Gold Exchange",                 tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 189, name: "Day Care",                      tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 193, name: "Restaurant Shelves",            tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 50, validRange: 0, canUpgrade: true },
  { id: 230, name: "Animal Cage",                   tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 3, maxHp: 50, validRange: 0, canUpgrade: true },
  { id: 231, name: "Art House",                     tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 3, maxHp: 50, validRange: 0, canUpgrade: true },
  { id: 232, name: "Water Tank",                    tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 3, maxHp: 50, validRange: 0, canUpgrade: true },
  { id: 233, name: "Bug Case",                      tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 3, maxHp: 50, validRange: 0, canUpgrade: true },
  { id: 234, name: "Cash Register",                 tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 238, name: "Reindeer Stable",               tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 242, name: "Flying Carpet",                 tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },


  { id: 162, name: "Monster Stable",                    tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 239, name: "Airport",                    tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 5, upgWood: 25, upgFood: 25, upgOre: 35, upgMystic: 50,
    maxUpgGrass: 100, maxUpgWood: 195, maxUpgFood: 185, maxUpgOre: 230, maxUpgMystic: 295,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 240, name: "Resource Center",                    tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 241, name: "Fishing Pond",                    tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 161, name: "Pitfall",                         tab: "amenity",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 5, upgWood: 0, upgFood: 5, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 100, maxUpgWood: 14, maxUpgFood: 85, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 50, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 226, name: "Bug Gathering Spot",               tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 14, canUpgrade: true },
  { id: 186, name: "Kairo King Statue",                tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 1, upgFood: 0, upgOre: 0, upgMystic: 3,
    maxUpgGrass: 15, maxUpgWood: 75, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 60,
    minHp: 50, maxHp: 500, validRange: 0, canUpgrade: true },
  // -- Indoors ---------------------------------------------------------------
  { id: 73 , name: "Temporary Shelter",             tab: "amenity",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 5, maxHp: 500, validRange: 0, canUpgrade: true },
  { id: 98 , name: "Hard Bed",                      tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 99 , name: "Bed",                           tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 100, name: "Royal Bed",                     tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 101, name: "Double Bed",                    tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 106, name: "Chair",                         tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 2, upgWood: 5, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 85, maxUpgWood: 95, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 107, name: "Royal Room",                    tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 108, name: "Research Lab",                  tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 109, name: "Hospital",                      tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 110, name: "Accessory Workshop",            tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 8, upgFood: 0, upgOre: 4, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 110, maxUpgFood: 12, maxUpgOre: 75, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 111, name: "Cooking Station",               tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 8, upgFood: 0, upgOre: 4, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 110, maxUpgFood: 12, maxUpgOre: 75, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 112, name: "Recovery Station",              tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 113, name: "Treasure Analysis Lab",         tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 114, name: "Furniture Workbench",           tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 8, upgFood: 0, upgOre: 4, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 110, maxUpgFood: 12, maxUpgOre: 75, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 115, name: "Weapon Workbench",              tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 8, upgFood: 0, upgOre: 4, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 110, maxUpgFood: 12, maxUpgOre: 75, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 116, name: "Armor Workbench",               tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 8, upgFood: 0, upgOre: 4, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 110, maxUpgFood: 12, maxUpgOre: 75, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 117, name: "Skill Workbench",               tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 8, upgFood: 0, upgOre: 0, upgMystic: 5,
    maxUpgGrass: 15, maxUpgWood: 110, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 70,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 118, name: "Item Workbench",                tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 8, upgFood: 0, upgOre: 4, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 110, maxUpgFood: 12, maxUpgOre: 75, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 119, name: "Decorative Plant",              tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 2, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 120, name: "Tomato",                        tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 2, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 121, name: "Flowers",                       tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 1, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 75, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 122, name: "Pansy",                         tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 1, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 75, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 123, name: "Glittering Stone",              tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 2, upgMystic: 2,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 65, maxUpgMystic: 55,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 124, name: "Dining Table",                  tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 2, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 125, name: "Couch",                         tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 2, upgWood: 4, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 85, maxUpgWood: 90, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 126, name: "Candle",                        tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 0, upgFood: 1, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 14, maxUpgFood: 65, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 127, name: "Tree Nursery",                  tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 128, name: "Decorative Armor",              tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 0, upgFood: 0, upgOre: 3, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 70, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 129, name: "Red Carpet",                    tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 130, name: "Fluffy Carpet",                 tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 131, name: "Black Mat",                     tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 135, name: "Rejuvenating Bath",             tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 3, upgFood: 0, upgOre: 2, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 65, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 136, name: "Rainwater Barrel",              tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 1, upgFood: 0, upgOre: 4, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 75, maxUpgFood: 12, maxUpgOre: 75, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 137, name: "Fireplace",                     tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 3, upgFood: 0, upgOre: 1, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 60, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 138, name: "Tool Workshop",                 tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 139, name: "Kitchen Shelves",               tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 2, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 140, name: "Bathtub",                       tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 2, upgFood: 0, upgOre: 4, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 75, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 141, name: "Chest of Drawers",              tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 2, upgWood: 4, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 85, maxUpgWood: 90, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 142, name: "Stove",                         tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 2, upgFood: 0, upgOre: 4, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 75, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 143, name: "Flower Vase",                   tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 144, name: "Animal Figurine",               tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 145, name: "Vanity Mirror",                 tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 3, upgMystic: 1,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 70, maxUpgMystic: 50,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 146, name: "Cooking Counter",               tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 2, upgFood: 0, upgOre: 2, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 65, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 147, name: "Shelf",                         tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 3, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 148, name: "Desk",                          tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 3, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 149, name: "Window",                        tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 150, name: "Bookshelf",                     tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 2, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 151, name: "Dresser",                       tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 2, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 80, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 152, name: "Ore Workbench",                 tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 153, name: "Study Desk",                    tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 1, upgWood: 3, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 80, maxUpgWood: 85, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 154, name: "Friend Bed",                    tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 155, name: "Guest Bed",                     tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 158, name: "Church",                        tab: "indoors",  size: "2×2",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 182, name: "Ancestor Statue",               tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 236, name: "Santa Room",                    tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },
  { id: 237, name: "Decorative Sled",               tab: "indoors",  size: "",
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 15, maxUpgWood: 14, maxUpgFood: 12, maxUpgOre: 10, maxUpgMystic: 8,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: true },

  // -- Map-unlocked ----------------------------------------------------------
  // These facilities are unlocked by clearing map tiles at the listed level.
  // Source: community spreadsheet (Kingdom Adventurers EN - Map.csv)
  { id: 172, name: "Ranking Board",         tab: "map",  size: "2×2", mapUnlock:   2,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 171, name: "Trophy Room",           tab: "map",  size: "2×2", mapUnlock:   3,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 167, name: "Briefing Room",         tab: "map",  size: "2×2", mapUnlock:   5,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 7,   name: "Port",                  tab: "map",  size: "2×2", mapUnlock:   7,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 195, name: "Cabin",                 tab: "map",  size: "2×2", mapUnlock:   8,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 166, name: "Friend Post Office",    tab: "map",  size: "2×2", mapUnlock:  10,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 175, name: "Material Shop",         tab: "map",  size: "2×2", mapUnlock:  10,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 165, name: "Master Smithy",         tab: "map",  size: "2×2", mapUnlock:  11,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 170, name: "Monster Farm",          tab: "map",  size: "2×2", mapUnlock:  14,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 181, name: "Underground Arena",     tab: "map",  size: "2×2", mapUnlock:  20,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 169, name: "Treasure Room",         tab: "map",  size: "2×2", mapUnlock:  21,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 168, name: "Weekly Conquest Bonus", tab: "map",  size: "2×2", mapUnlock:  22,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 198, name: "Movers",                tab: "map",  size: "2×2", mapUnlock:  23,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 173, name: "Friends Agency",        tab: "map",  size: "2×2", mapUnlock:  30,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 200, name: "Equipment Exchange",    tab: "map",  size: "2×2", mapUnlock:  34,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 174, name: "Job Center",            tab: "map",  size: "2×2", mapUnlock:  35,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 201, name: "Trading Post",          tab: "map",  size: "2×2", mapUnlock:  40,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 177, name: "Instructor's Room",     tab: "map",  size: "2×2", mapUnlock:  41,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 10,  name: "Port",                  tab: "map",  size: "2×2", mapUnlock:  44,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 178, name: "Monster Fusion Lab",    tab: "map",  size: "2×2", mapUnlock:  45,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 180, name: "Kairo Room",            tab: "map",  size: "2×2", mapUnlock:  58,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 196, name: "Legendary Cave",        tab: "map",  size: "2×2", mapUnlock: 120,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
  { id: 202, name: "Date Spot",             tab: "map",  size: "2×2", mapUnlock: 135,
    minGrass: 0, minWood: 0, minFood: 0, minOre: 0, minMystic: 0,
    maxGrass: 0, maxWood: 0, maxFood: 0, maxOre: 0, maxMystic: 0,
    upgGrass: 0, upgWood: 0, upgFood: 0, upgOre: 0, upgMystic: 0,
    maxUpgGrass: 0, maxUpgWood: 0, maxUpgFood: 0, maxUpgOre: 0, maxUpgMystic: 0,
    minHp: 0, maxHp: 0, validRange: 0, canUpgrade: false },
];

