export type KairoEquipmentName =
  | "A/ Kairo Sword"
  | "A/ Kairo Hammer"
  | "A/ Kairo Lance"
  | "A/ Kairo Bow"
  | "A/ Kairo Gun";

export interface EquipmentExchangeEntry {
  inputId: number;
  inputName: string;
  outputName: KairoEquipmentName;
  startPrice: number;
  priceStep: number;
  copperCoinPrice: number;
}

export const EQUIPMENT_EXCHANGE_OUTPUTS: KairoEquipmentName[] = [
  "A/ Kairo Sword",
  "A/ Kairo Hammer",
  "A/ Kairo Lance",
  "A/ Kairo Bow",
  "A/ Kairo Gun",
];

export const EQUIPMENT_EXCHANGE_ENTRIES: EquipmentExchangeEntry[] = [
  { inputId: 274, inputName: "B/ Blue Pendant", outputName: "A/ Kairo Bow", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 300, inputName: "B/ Boots", outputName: "A/ Kairo Bow", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 303, inputName: "B/ Charm", outputName: "A/ Kairo Bow", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 283, inputName: "B/ Collar", outputName: "A/ Kairo Bow", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 309, inputName: "B/ Gold Bag", outputName: "A/ Kairo Bow", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 278, inputName: "B/ Golden Bracelet", outputName: "A/ Kairo Bow", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 291, inputName: "B/ Leather Gloves", outputName: "A/ Kairo Bow", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 305, inputName: "B/ Red Ribbon", outputName: "A/ Kairo Bow", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 293, inputName: "B/ Silver Earrings", outputName: "A/ Kairo Bow", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 287, inputName: "B/ Silver Ring", outputName: "A/ Kairo Bow", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 273, inputName: "C/ Amulet", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 302, inputName: "C/ Candle", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 308, inputName: "C/ Cloth Bag", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 290, inputName: "C/ Gloves", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 277, inputName: "C/ Magic Pendant", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 286, inputName: "C/ Pearl Ring", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 307, inputName: "C/ Wooden Carving", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 280, inputName: "C/ Wristband", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 279, inputName: "D/ Leather Band", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 298, inputName: "D/ Loafers", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 272, inputName: "D/ Necklace", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 285, inputName: "D/ Ring", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 282, inputName: "D/ Scarf", outputName: "A/ Kairo Bow", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 296, inputName: "E/ Leather Shoes", outputName: "A/ Kairo Bow", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 271, inputName: "E/ Locket", outputName: "A/ Kairo Bow", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 297, inputName: "F/ Wooden Sandals", outputName: "A/ Kairo Bow", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 170, inputName: "B/ Battle Axe", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 85, inputName: "B/ Big Bad Hammer", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 79, inputName: "B/ Commander's Spear", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 95, inputName: "B/ Commander's Sword", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 115, inputName: "B/ Destruction Sword", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 21, inputName: "B/ Diamond Staff", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 125, inputName: "B/ Flame Ninja Star", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 120, inputName: "B/ Frosty Sword", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 41, inputName: "B/ Hero Club", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 149, inputName: "B/ Hero Sword", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 164, inputName: "B/ Hunting Bow", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 45, inputName: "B/ Iron Club", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 105, inputName: "B/ Lightning Scalpel", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 135, inputName: "B/ Lightweight Sword", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 130, inputName: "B/ Master's Katana", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 100, inputName: "B/ Master's Knife", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 49, inputName: "B/ Morning Star", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 159, inputName: "B/ Musket", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 156, inputName: "B/ Paintbrush", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 74, inputName: "B/ Red Spear", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 25, inputName: "B/ Shining Staff", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 89, inputName: "B/ Silver Hammer", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 144, inputName: "B/ Sword of the Void", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 30, inputName: "B/ Thunder Staff", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 66, inputName: "B/ Tree Branch", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 70, inputName: "B/ Trident", outputName: "A/ Kairo Gun", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 34, inputName: "C/ Ancient Staff", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 155, inputName: "C/ Ancient Tome", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 60, inputName: "C/ Artistic Club", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 44, inputName: "C/ Club", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 148, inputName: "C/ Courage Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 48, inputName: "C/ Cudgel", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 143, inputName: "C/ Darkness Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 40, inputName: "C/ Elder Club", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 65, inputName: "C/ Folk Art Club", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 124, inputName: "C/ Giant Ninja Star", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 119, inputName: "C/ Ice Greatsword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 163, inputName: "C/ Infantry Bow", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 84, inputName: "C/ Iron Hammer", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 73, inputName: "C/ Iron Pike", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 54, inputName: "C/ Light Club", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 29, inputName: "C/ Lightning Staff", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 20, inputName: "C/ Magic Staff", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 94, inputName: "C/ Master's Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 78, inputName: "C/ Paladin's Spear", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 158, inputName: "C/ Rifle", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 139, inputName: "C/ Saint's Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 129, inputName: "C/ Shogun's Katana", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 104, inputName: "C/ Silver Scalpel", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 114, inputName: "C/ Silver Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 24, inputName: "C/ Spiked Staff", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 169, inputName: "C/ Steel Axe", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 134, inputName: "C/ Tempered Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 109, inputName: "C/ Tornado Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 138, inputName: "D/ Bastard Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 142, inputName: "D/ Black Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 162, inputName: "D/ Bow", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 108, inputName: "D/ Cutlass", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 28, inputName: "D/ Grief Staff", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 118, inputName: "D/ Ice Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 43, inputName: "D/ Ladle", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 88, inputName: "D/ Long Hammer", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 168, inputName: "D/ Lumberjack's Axe", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 47, inputName: "D/ Mace", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 69, inputName: "D/ Master's Spear", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 123, inputName: "D/ Ninja Star", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 147, inputName: "D/ Normal Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 39, inputName: "D/ Oak Club", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 157, inputName: "D/ Pistol", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 153, inputName: "D/ Research Guide", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 33, inputName: "D/ Royal Scepter", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 113, inputName: "D/ Sabre", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 99, inputName: "D/ Silver Knife", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 64, inputName: "D/ Spiked Club", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 93, inputName: "D/ Steel Sword", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 19, inputName: "D/ Sturdy Staff", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 59, inputName: "D/ The Spike", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 87, inputName: "E/ Basic Hammer", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 77, inputName: "E/ Bronze Spear", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 133, inputName: "E/ Copper Sword", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 72, inputName: "E/ Fisherman's Pike", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 42, inputName: "E/ Gnarly Club", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 27, inputName: "E/ Green Staff", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 117, inputName: "E/ Ice Knife", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 112, inputName: "E/ Infantry Sword", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 68, inputName: "E/ Iron Spear", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 98, inputName: "E/ Kitchen Knife", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 122, inputName: "E/ Kunai", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 137, inputName: "E/ Longish Sword", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 154, inputName: "E/ Magnifying Glass", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 83, inputName: "E/ Mallet", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 18, inputName: "E/ Metal Ore Staff", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 107, inputName: "E/ Pirate Sword", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 63, inputName: "E/ Pokey Stick", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 32, inputName: "E/ Red Staff", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 128, inputName: "E/ Samurai Sword", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 103, inputName: "E/ Scalpel", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 38, inputName: "E/ Sturdy Club", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 92, inputName: "E/ Sword", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 58, inputName: "E/ Tough Club", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 23, inputName: "E/ Wooden Wand", outputName: "A/ Kairo Gun", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 167, inputName: "F/ Adze", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 57, inputName: "F/ Bludgeon", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 132, inputName: "F/ Bronze Sword", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 97, inputName: "F/ Fruit Knife", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 22, inputName: "F/ Iron Staff", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 152, inputName: "F/ Novel", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 52, inputName: "F/ Prayer Club", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 127, inputName: "F/ Simple Katana", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 102, inputName: "F/ Tiny Knife", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 82, inputName: "F/ Tiny Mallet", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 37, inputName: "F/ Wooden Club", outputName: "A/ Kairo Gun", startPrice: 20, priceStep: 16, copperCoinPrice: 20 },
  { inputId: 67, inputName: "F/ Wooden Spear", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 62, inputName: "F/ Wooden Stick", outputName: "A/ Kairo Gun", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 53, inputName: "G/ Holy Club", outputName: "A/ Kairo Gun", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 266, inputName: "B/ Iron Headpiece", outputName: "A/ Kairo Hammer", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 265, inputName: "B/ Iron Mask", outputName: "A/ Kairo Hammer", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 255, inputName: "B/ Mystic Hat", outputName: "A/ Kairo Hammer", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 257, inputName: "B/ Shampoo Hat", outputName: "A/ Kairo Hammer", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 253, inputName: "B/ Wizard's Hat", outputName: "A/ Kairo Hammer", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 263, inputName: "C/ Bronze Headpiece", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 262, inputName: "C/ Guard Helmet", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 264, inputName: "C/ Helmet", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 252, inputName: "C/ Mage's Hat", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 256, inputName: "C/ Mail Coif", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 238, inputName: "D/ Bandana", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 240, inputName: "D/ Forehead Guard", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 261, inputName: "D/ Lookout Hat", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 251, inputName: "D/ Magic Hat", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 239, inputName: "D/ Ninja Headband", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 248, inputName: "D/ Winged Bandana", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 249, inputName: "D/ Winged Hat", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 250, inputName: "D/ Winged Helm", outputName: "A/ Kairo Hammer", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 245, inputName: "E/ Angel's Halo", outputName: "A/ Kairo Hammer", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 247, inputName: "E/ Director's Beret", outputName: "A/ Kairo Hammer", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 235, inputName: "E/ Hat (B)", outputName: "A/ Kairo Hammer", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 237, inputName: "E/ Hat (R)", outputName: "A/ Kairo Hammer", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 236, inputName: "E/ Helmet", outputName: "A/ Kairo Hammer", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 246, inputName: "E/ Pirate Hat", outputName: "A/ Kairo Hammer", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 232, inputName: "F/ Alice Band", outputName: "A/ Kairo Hammer", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 231, inputName: "F/ Bandana", outputName: "A/ Kairo Hammer", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 241, inputName: "F/ Chef Hat", outputName: "A/ Kairo Hammer", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 243, inputName: "F/ Hat", outputName: "A/ Kairo Hammer", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 233, inputName: "F/ Headband", outputName: "A/ Kairo Hammer", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 244, inputName: "F/ Holy Hat", outputName: "A/ Kairo Hammer", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 242, inputName: "F/ Top Hat", outputName: "A/ Kairo Hammer", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 234, inputName: "F/ Turban", outputName: "A/ Kairo Hammer", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 193, inputName: "B/ Green Shield", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 192, inputName: "B/ Legendary Shield (B)", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 198, inputName: "B/ Legendary Shield (R)", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 187, inputName: "B/ Scholar's Shield", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 185, inputName: "B/ Shell Shield", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 199, inputName: "C/ Conqueror's Shield", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 8 },
  { inputId: 197, inputName: "C/ Demonic Shield", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 8 },
  { inputId: 191, inputName: "C/ Nightmare Shield", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 8 },
  { inputId: 182, inputName: "C/ Noble Shield", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 8 },
  { inputId: 189, inputName: "D/ Folk Art Shield", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 14 },
  { inputId: 181, inputName: "D/ Iron Shield", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 14 },
  { inputId: 190, inputName: "D/ Sturdy Shield", outputName: "A/ Kairo Lance", startPrice: 2, priceStep: 2, copperCoinPrice: 14 },
  { inputId: 180, inputName: "E/ Buckler", outputName: "A/ Kairo Lance", startPrice: 4, priceStep: 4, copperCoinPrice: 18 },
  { inputId: 179, inputName: "E/ Infantry Shield", outputName: "A/ Kairo Lance", startPrice: 4, priceStep: 4, copperCoinPrice: 18 },
  { inputId: 178, inputName: "F/ Leather Shield", outputName: "A/ Kairo Lance", startPrice: 6, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 177, inputName: "F/ Wooden Shield", outputName: "A/ Kairo Lance", startPrice: 6, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 225, inputName: "B/ Bronze Armor", outputName: "A/ Kairo Sword", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 210, inputName: "B/ Dress", outputName: "A/ Kairo Sword", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 215, inputName: "B/ Fine Robe", outputName: "A/ Kairo Sword", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 219, inputName: "B/ Purple Cape", outputName: "A/ Kairo Sword", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 226, inputName: "B/ Silver Armor", outputName: "A/ Kairo Sword", startPrice: 2, priceStep: 2, copperCoinPrice: 2 },
  { inputId: 213, inputName: "C/ Coat", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 218, inputName: "C/ Durable Cape", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 212, inputName: "C/ Fur Coat", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 223, inputName: "C/ Leather Armor", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 224, inputName: "C/ Light Mail", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 216, inputName: "C/ Men's Kimono", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 214, inputName: "C/ Robe", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 209, inputName: "C/ Skirt", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 8 },
  { inputId: 217, inputName: "D/ Cape", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 208, inputName: "D/ Chain Mail", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 222, inputName: "D/ Iron Chest Guard", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 211, inputName: "D/ Pajamas", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 206, inputName: "D/ Stylish Garment", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 207, inputName: "D/ Thick Garment", outputName: "A/ Kairo Sword", startPrice: 4, priceStep: 4, copperCoinPrice: 14 },
  { inputId: 205, inputName: "E/ Durable Garment", outputName: "A/ Kairo Sword", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 221, inputName: "E/ Leather Chest Guard", outputName: "A/ Kairo Sword", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 204, inputName: "E/ Yellow Garment", outputName: "A/ Kairo Sword", startPrice: 6, priceStep: 6, copperCoinPrice: 18 },
  { inputId: 203, inputName: "F/ Common Garment", outputName: "A/ Kairo Sword", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 202, inputName: "F/ Linen Garment", outputName: "A/ Kairo Sword", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
  { inputId: 201, inputName: "F/ Loincloth", outputName: "A/ Kairo Sword", startPrice: 8, priceStep: 6, copperCoinPrice: 20 },
];

export function rankLabel(name: string) {
  const match = name.match(/^([A-Z])\//);
  return match?.[1] ?? "?";
}
