// Generated from Kairosoft Wiki's Monsters (Kingdom Adventurers) page.
// Source: https://kairosoft.fandom.com/wiki/Monsters_(Kingdom_Adventurers)

export const MONSTER_ICON_MAP: Record<string, string> = {
  "Aloha Kairobot": "/monster-icons/aloha-kairobot.jpg",
  "Alpacavalier": "/monster-icons/alpacavalier.jpg",
  "Assault Bee": "/monster-icons/assault-bee.jpg",
  "Axey Lottle": "/monster-icons/axey-lottle.jpg",
  "Big-Bellied Frog": "/monster-icons/big-bellied-frog.jpg",
  "Brawlbunn": "/monster-icons/brawlbunn.jpg",
  "Broccolin": "/monster-icons/broccolin.jpg",
  "Brock Rockson": "/monster-icons/brock-rockson.jpg",
  "Brute-Belly Jackson": "/monster-icons/brute-belly-jackson.jpg",
  "Cactitus": "/monster-icons/cactitus.jpg",
  "Chimpan Z": "/monster-icons/chimpan-z.jpg",
  "Cobrajah": "/monster-icons/cobrajah.jpg",
  "Crabella": "/monster-icons/crabella.jpg",
  "Craggy Conepoke": "/monster-icons/craggy-conepoke.jpg",
  "Creeperbloom": "/monster-icons/creeperbloom.jpg",
  "Dark Smoke": "/monster-icons/dark-smoke.jpg",
  "Dark Tinkle": "/monster-icons/dark-tinkle.jpg",
  "Demonic Wairobot": "/monster-icons/demonic-wairobot.jpg",
  "Desertail": "/monster-icons/desertail.jpg",
  "Diamondoom": "/monster-icons/diamondoom.jpg",
  "Dizzy Butterfly": "/monster-icons/dizzy-butterfly.jpg",
  "Drago": "/monster-icons/drago.jpg",
  "Dragolion": "/monster-icons/dragolion.jpg",
  "Dried-Out Fish": "/monster-icons/dried-out-fish.jpg",
  "Dropplet": "/monster-icons/dropplet.jpg",
  "Ducky Bills": "/monster-icons/ducky-bills.jpg",
  "Earth Dragon": "/monster-icons/earth-dragon.jpg",
  "Ember": "/monster-icons/ember.jpg",
  "Erupterror": "/monster-icons/erupterror.jpg",
  "Fake Apple": "/monster-icons/fake-apple.jpg",
  "Falcone": "/monster-icons/falcone.jpg",
  "Fashion Golem": "/monster-icons/fashion-golem.jpg",
  "Fiery Snow": "/monster-icons/fiery-snow.jpg",
  "Firaj": "/monster-icons/firaj.jpg",
  "Flame Dragon": "/monster-icons/flame-dragon.jpg",
  "Flaming Hand": "/monster-icons/flaming-hand.jpg",
  "Flatsy Maxie": "/monster-icons/flatsy-maxie.jpg",
  "Flint Rockson": "/monster-icons/flint-rockson.jpg",
  "Freezard": "/monster-icons/freezard.jpg",
  "Fugitive Egg": "/monster-icons/fugitive-egg.jpg",
  "Gasper": "/monster-icons/gasper.jpg",
  "Gelatintin": "/monster-icons/gelatintin.jpg",
  "Ghost": "/monster-icons/ghost.jpg",
  "Giant Alraune": "/monster-icons/giant-alraune.jpg",
  "Gifty": "/monster-icons/gifty.jpg",
  "Glacie": "/monster-icons/glacie.jpg",
  "Gloom Shroom": "/monster-icons/gloom-shroom.jpg",
  "Go-Go Golem": "/monster-icons/go-go-golem.jpg",
  "Gobman": "/monster-icons/gobman.jpg",
  "Granitron": "/monster-icons/granitron.jpg",
  "Grizzly Bearington": "/monster-icons/grizzly-bearington.jpg",
  "Hoppity": "/monster-icons/hoppity.jpg",
  "Horned Rock": "/monster-icons/horned-rock.jpg",
  "Hotalot Devil": "/monster-icons/hotalot-devil.jpg",
  "Howling Wraith": "/monster-icons/howling-wraith.jpg",
  "Human-Faced Tree": "/monster-icons/human-faced-tree.jpg",
  "Icebox": "/monster-icons/icebox.jpg",
  "Icebug": "/monster-icons/icebug.jpg",
  "Igluu": "/monster-icons/igluu.jpg",
  "Ironclad Pincher": "/monster-icons/ironclad-pincher.jpg",
  "Kairobot": "/monster-icons/kairobot.jpg",
  "Kairobot Knight": "/monster-icons/kairobot-knight.jpg",
  "Kairobot Mage": "/monster-icons/kairobot-mage.jpg",
  "Kid Slime": "/monster-icons/kid-slime.jpg",
  "Lava Bat": "/monster-icons/lava-bat.jpg",
  "Lavallie": "/monster-icons/lavallie.jpg",
  "Lococonut": "/monster-icons/lococonut.jpg",
  "Lord of the Frier": "/monster-icons/lord-of-the-frier.jpg",
  "Lurkeel": "/monster-icons/lurkeel.jpg",
  "Machbat": "/monster-icons/machbat.jpg",
  "Magmafish": "/monster-icons/magmafish.jpg",
  "Mammoth Caterpillar": "/monster-icons/mammoth-caterpillar.jpg",
  "Mandragora": "/monster-icons/mandragora.jpg",
  "Marshmaid": "/monster-icons/marshmaid.jpg",
  "Metabok": "/monster-icons/metabok.jpg",
  "Metalbok": "/monster-icons/metalbok.jpg",
  "Metamorphic Stone": "/monster-icons/metamorphic-stone.jpg",
  "Midnight Snack Mervin": "/monster-icons/midnight-snack-mervin.jpg",
  "Mimico": "/monster-icons/mimico.jpg",
  "Mirage Eel": "/monster-icons/mirage-eel.jpg",
  "Mister X": "/monster-icons/mister-x.jpg",
  "Mochipork": "/monster-icons/mochipork.jpg",
  "Mossy Shroom": "/monster-icons/mossy-shroom.jpg",
  "Mudchomp": "/monster-icons/mudchomp.jpg",
  "Murderbirb": "/monster-icons/murderbirb.jpg",
  "Octoman": "/monster-icons/octoman.jpg",
  "One-Eyed Rock": "/monster-icons/one-eyed-rock.jpg",
  "Ore Crab": "/monster-icons/ore-crab.jpg",
  "Pandah": "/monster-icons/pandah.jpg",
  "Pillbug": "/monster-icons/pillbug.jpg",
  "Polar Pupper": "/monster-icons/polar-pupper.jpg",
  "Poochington": "/monster-icons/poochington.jpg",
  "Queen Cactitus": "/monster-icons/queen-cactitus.jpg",
  "Raging Boar": "/monster-icons/raging-boar.jpg",
  "Renegade Bird": "/monster-icons/renegade-bird.jpg",
  "Renegade Chick": "/monster-icons/renegade-chick.jpg",
  "Rock Golem": "/monster-icons/rock-golem.jpg",
  "Rockclad Ladybug": "/monster-icons/rockclad-ladybug.jpg",
  "Sandbag": "/monster-icons/sandbag.jpg",
  "Sandworm": "/monster-icons/sandworm.jpg",
  "Screaming Caterpillar": "/monster-icons/screaming-caterpillar.jpg",
  "Shaggy Bug": "/monster-icons/shaggy-bug.jpg",
  "Shockfish": "/monster-icons/shockfish.jpg",
  "Skullbug": "/monster-icons/skullbug.jpg",
  "Skullene": "/monster-icons/skullene.jpg",
  "Slurper Z": "/monster-icons/slurper-z.jpg",
  "Snake Ice": "/monster-icons/snake-ice.jpg",
  "Snappish Turtle": "/monster-icons/snappish-turtle.jpg",
  "Sneakyfish": "/monster-icons/sneakyfish.jpg",
  "Snow Dragon": "/monster-icons/snow-dragon.jpg",
  "Snowbug": "/monster-icons/snowbug.jpg",
  "Stacey Ditz": "/monster-icons/stacey-ditz.jpg",
  "Steel-Stomach Jackie": "/monster-icons/steel-stomach-jackie.jpg",
  "Stinger": "/monster-icons/stinger.jpg",
  "Swamp Toad": "/monster-icons/swamp-toad.jpg",
  "Telltail Fish": "/monster-icons/telltail-fish.jpg",
  "Terror Tree": "/monster-icons/terror-tree.jpg",
  "Thornster": "/monster-icons/thornster.jpg",
  "Tinyturt": "/monster-icons/tinyturt.jpg",
  "Trapling": "/monster-icons/trapling.jpg",
  "Treasure Sack": "/monster-icons/treasure-sack.jpg",
  "Triplet Rocks": "/monster-icons/triplet-rocks.jpg",
  "Tutanhop": "/monster-icons/tutanhop.jpg",
  "Undead Cap'n": "/monster-icons/undead-cap-n.jpg",
  "Undead Pirate": "/monster-icons/undead-pirate.jpg",
  "Vince Balboa": "/monster-icons/vince-balboa.jpg",
  "Volcanus": "/monster-icons/volcanus.jpg",
  "Wairobot": "/monster-icons/wairobot.jpg",
  "Wairobot Mage": "/monster-icons/wairobot-mage.jpg",
  "Wairobot Warrior": "/monster-icons/wairobot-warrior.jpg",
  "Wild Grass": "/monster-icons/wild-grass.jpg",
  "Wild Shrub": "/monster-icons/wild-shrub.jpg"
};
